<?php

namespace App\Services\Integrations\Adapters;

use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Throwable;

/**
 * Wialon (Gurtam) Remote API — the platform behind gps.tawasolmap.com. One access token (generated by the account
 * owner on {base}/login.html) opens a session (`token/login` → sid); the session is reused for a few minutes and
 * reopened once when the server says it expired (error 1). `core/search_items` returns every unit the token may see
 * with its last position; a unit is matched to a vehicle by the vehicle's `gps_device_id` = unit IMEI (uid), name or id.
 */
class WialonGps implements GpsAdapter
{
    public const SESSION_CACHE = 'wialon:sid';

    private const SESSION_MINUTES = 4; // Wialon closes idle sessions after 5

    /** base(1) + advanced properties incl. uid / phone (0x100) + last message and position (0x400) */
    private const UNIT_FLAGS = 0x501;

    private const ERRORS = [1 => 'invalid session', 2 => 'invalid service', 3 => 'invalid result', 4 => 'invalid input', 5 => 'error performing request', 6 => 'unknown error', 7 => 'access denied', 8 => 'invalid user name or password', 1001 => 'no messages for selected interval', 1003 => 'too many requests', 1004 => 'limit of concurrent requests', 1011 => 'too many requests'];

    public function __construct(private readonly string $baseUrl, private readonly string $token, private readonly int $timeoutMs = 10000) {}

    public function configured(): bool
    {
        return true;
    }

    /** @return array{ok:bool, data?:mixed, code?:int, detail?:string} */
    private function call(string $svc, array $params, ?string $sid = null): array
    {
        try {
            $query = ['svc' => $svc, 'params' => json_encode($params, JSON_UNESCAPED_UNICODE)] + ($sid ? ['sid' => $sid] : []);
            $res = Http::timeout($this->timeoutMs / 1000)->asForm()->post(rtrim($this->baseUrl, '/').'/wialon/ajax.html', $query);
            if (! $res->successful()) {
                return ['ok' => false, 'detail' => "HTTP {$res->status()}"];
            }
            $data = $res->json();
            if (is_array($data) && array_key_exists('error', $data) && count($data) <= 2) {
                $code = (int) $data['error'];

                return ['ok' => false, 'code' => $code, 'detail' => 'Wialon error '.$code.' — '.(self::ERRORS[$code] ?? 'unknown').(isset($data['reason']) ? ' ('.Pending::snippet((string) $data['reason'], 60).')' : '')];
            }

            return ['ok' => true, 'data' => $data];
        } catch (Throwable $e) {
            $detail = Pending::describeError($e);
            Log::warning("wialon {$svc} failed: {$detail}");

            return ['ok' => false, 'detail' => $detail];
        }
    }

    /** @return array{ok:bool, sid?:string, detail?:string, user?:string} */
    private function login(): array
    {
        $r = $this->call('token/login', ['token' => $this->token]);
        if (! $r['ok']) {
            return $r;
        }
        $sid = $r['data']['eid'] ?? null;
        if (! is_string($sid) || $sid === '') {
            return ['ok' => false, 'detail' => 'login answered without a session id'];
        }
        Cache::put(self::SESSION_CACHE, $sid, now()->addMinutes(self::SESSION_MINUTES));

        return ['ok' => true, 'sid' => $sid, 'user' => (string) ($r['data']['user']['nm'] ?? '')];
    }

    /** Runs a service inside a session, logging in first and again once when the cached session has expired. */
    private function inSession(string $svc, array $params): array
    {
        $sid = Cache::get(self::SESSION_CACHE);
        if (! $sid) {
            $l = $this->login();
            if (! $l['ok']) {
                return $l;
            }
            $sid = $l['sid'];
        }
        $r = $this->call($svc, $params, $sid);
        if (! $r['ok'] && ($r['code'] ?? null) === 1) { // session expired server-side
            Cache::forget(self::SESSION_CACHE);
            $l = $this->login();
            if (! $l['ok']) {
                return $l;
            }
            $r = $this->call($svc, $params, $l['sid']);
        }
        if ($r['ok']) {
            Cache::put(self::SESSION_CACHE, $sid, now()->addMinutes(self::SESSION_MINUTES)); // activity keeps the session alive
        }

        return $r;
    }

    /** Checks the token: → { ok, user, detail } */
    public function probe(): array
    {
        $l = $this->login();

        return $l['ok'] ? ['ok' => true, 'user' => $l['user'], 'detail' => 'session opened'] : ['ok' => false, 'detail' => $l['detail']];
    }

    /**
     * Every unit the token can see, with its last position.
     *
     * @return array{status:string, units?:list<array{id:string, name:string, uid:?string, phone:?string, lat:?float, lng:?float, speedKph:?float, course:?int, at:?string}>, detail?:string}
     */
    public function units(): array
    {
        $r = $this->inSession('core/search_items', [
            'spec' => ['itemsType' => 'avl_unit', 'propName' => 'sys_name', 'propValueMask' => '*', 'sortType' => 'sys_name'],
            'force' => 1, 'flags' => self::UNIT_FLAGS, 'from' => 0, 'to' => 0,
        ]);
        if (! $r['ok']) {
            return ['status' => 'error', 'detail' => $r['detail']];
        }
        $units = [];
        foreach ((array) ($r['data']['items'] ?? []) as $u) {
            $pos = is_array($u['pos'] ?? null) ? $u['pos'] : null;
            $t = $pos['t'] ?? $u['lmsg']['t'] ?? null;
            $units[] = [
                'id' => (string) ($u['id'] ?? ''), 'name' => (string) ($u['nm'] ?? ''), 'uid' => isset($u['uid']) ? (string) $u['uid'] : null, 'phone' => isset($u['ph']) ? (string) $u['ph'] : null,
                'lat' => isset($pos['y']) && is_numeric($pos['y']) ? (float) $pos['y'] : null, 'lng' => isset($pos['x']) && is_numeric($pos['x']) ? (float) $pos['x'] : null,
                'speedKph' => isset($pos['s']) && is_numeric($pos['s']) ? (float) $pos['s'] : null, 'course' => isset($pos['c']) && is_numeric($pos['c']) ? (int) $pos['c'] : null,
                'at' => is_numeric($t) ? gmdate('Y-m-d\TH:i:s\Z', (int) $t) : null,
            ];
        }

        return ['status' => 'ok', 'units' => $units];
    }

    /** Finds the unit whose IMEI / name / id equals the reference the vehicle stores in `gps_device_id`. */
    public static function match(array $units, ?string $deviceRef): ?array
    {
        $ref = mb_strtolower(trim((string) $deviceRef));
        if ($ref === '') {
            return null;
        }
        foreach ($units as $u) {
            if (in_array($ref, array_map(fn ($v) => mb_strtolower(trim((string) $v)), [$u['uid'], $u['name'], $u['id']]), true)) {
                return $u;
            }
        }

        return null;
    }

    public function getVehiclePosition(string $vehicleCode): array
    {
        $r = $this->units();
        if ($r['status'] !== 'ok') {
            return ['status' => 'error', 'vehicleCode' => $vehicleCode, 'detail' => $r['detail']];
        }
        $u = self::match($r['units'], $vehicleCode);
        if (! $u) {
            return ['status' => 'error', 'vehicleCode' => $vehicleCode, 'detail' => 'no unit matches this reference'];
        }
        if ($u['lat'] === null || $u['lng'] === null) {
            return ['status' => 'error', 'vehicleCode' => $vehicleCode, 'detail' => 'unit has no position yet'];
        }

        return ['status' => 'ok', 'vehicleCode' => $vehicleCode, 'lat' => $u['lat'], 'lng' => $u['lng'], 'speedKph' => $u['speedKph'], 'at' => $u['at'] ?? now()->toIso8601ZuluString()];
    }

    /**
     * The unit's recorded positions between two times (its message history on the Wialon server), oldest first — the
     * real track the device reported, not only the fixes this server happened to sample. At most $max messages; `more`
     * says the window held more (ask again from the last `at`).
     *
     * @return array{status:string, points?:list<array{lat:float, lng:float, speedKph:?float, course:?int, at:string}>, more?:bool, detail?:string}
     */
    public function track(string $unitId, int $from, int $to, int $max = 5000): array
    {
        // flags / mask: data messages (type 0x0000 in the 0xFF00 type bits) that carry a position (0x0001)
        $r = $this->inSession('messages/load_interval', ['itemId' => (int) $unitId, 'timeFrom' => $from, 'timeTo' => $to, 'flags' => 0x0001, 'flagsMask' => 0xFF01, 'loadCount' => $max]);
        if (! $r['ok']) {
            return ($r['code'] ?? null) === 1001 ? ['status' => 'ok', 'points' => [], 'more' => false] : ['status' => 'error', 'detail' => $r['detail']];
        }
        $messages = (array) ($r['data']['messages'] ?? []);
        $points = [];
        foreach ($messages as $m) {
            $pos = is_array($m['pos'] ?? null) ? $m['pos'] : null;
            if (! $pos || ! is_numeric($pos['y'] ?? null) || ! is_numeric($pos['x'] ?? null) || ! is_numeric($m['t'] ?? null) || ((float) $pos['y'] === 0.0 && (float) $pos['x'] === 0.0)) {
                continue;
            }
            $points[] = [
                'lat' => (float) $pos['y'], 'lng' => (float) $pos['x'],
                'speedKph' => is_numeric($pos['s'] ?? null) ? (float) $pos['s'] : null, 'course' => is_numeric($pos['c'] ?? null) ? (int) $pos['c'] : null,
                'at' => gmdate('Y-m-d\TH:i:s\Z', (int) $m['t']),
            ];
        }
        $this->inSession('messages/unload', []); // frees the message buffer the session holds

        return ['status' => 'ok', 'points' => $points, 'more' => count($messages) >= $max];
    }

    /** Reefer temperature needs the unit's sensor configuration (differs per installer) — honestly not read here. */
    public function getVehicleTemperature(string $vehicleCode): array
    {
        return ['status' => Pending::STATUS, 'vehicleCode' => $vehicleCode, 'detail' => 'temperature sensors are not mapped for this provider'];
    }
}
