// One import for the shared UI kit:  import { Btn, Chip, DataTable, FormDrawer, … } from '@/components';
export { default as Btn } from './Btn.vue';
export { default as Chip } from './Chip.vue';
export { chipStyle } from './chip';
export { default as KpiCard } from './KpiCard.vue';
export { default as KpiGrid } from './KpiGrid.vue';
export { default as DataTable } from './DataTable.vue';
export { default as Field } from './Field.vue';
export { default as TextInput } from './TextInput.vue';
export { default as NumberInput } from './NumberInput.vue';
export { default as SelectInput } from './SelectInput.vue';
export { default as TextArea } from './TextArea.vue';
export { default as DateInput } from './DateInput.vue';
export { default as ScanInput } from './ScanInput.vue';
export { default as ScanButton } from './ScanButton.vue';
export { default as BarcodeScanner } from './BarcodeScanner.vue';
export { default as PillChoice } from './PillChoice.vue';
export { optL, optV } from './options';
export { default as FormDrawer } from './FormDrawer.vue';
export { default as Tabs } from './Tabs.vue';
export { default as Timeline } from './Timeline.vue';
export { default as Stepper } from './Stepper.vue';
export { default as ProgressBar } from './ProgressBar.vue';
export { default as StackedBar } from './StackedBar.vue';
export { default as SectionCard } from './SectionCard.vue';
export { default as EmptyState } from './EmptyState.vue';
export { default as KV } from './KV.vue';
// layout pieces pages use directly
export { default as Drawer } from '../layout/Drawer.vue';
export { default as Modal } from '../layout/Modal.vue';
export { default as ErrorBanner } from '../layout/ErrorBanner.vue';
export { default as PageHead } from '../layout/PageHead.vue';
export { default as Icon } from '../layout/Icon.vue';
