<?php

// GENERATED by tools/prisma-to-laravel.mjs from docs/reference/schema.prisma.
// Do not hand-edit: change the generator, or add a new migration for schema changes.

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('username')->unique();
            $table->string('email')->nullable()->unique();
            $table->string('password_hash');
            $table->string('name_ar');
            $table->string('name_en');
            $table->string('initials')->nullable();
            $table->boolean('active')->default(true);
            $table->boolean('must_change_password')->default(false);
            $table->dateTime('last_login_at', 3)->nullable();
            $table->timestamps(3);
        });

        Schema::create('roles', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('key')->unique();
            $table->string('name_ar');
            $table->string('name_en');
            $table->boolean('is_system')->default(true);
        });

        Schema::create('permissions', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('key')->unique();
            $table->text('description')->nullable();
        });

        Schema::create('user_roles', function (Blueprint $table) {
            $table->ulid('user_id');
            $table->ulid('role_id');
            $table->primary(['user_id', 'role_id']);
        });

        Schema::create('role_permissions', function (Blueprint $table) {
            $table->ulid('role_id');
            $table->ulid('permission_id');
            $table->primary(['role_id', 'permission_id']);
        });

        Schema::create('user_warehouses', function (Blueprint $table) {
            $table->ulid('user_id');
            $table->ulid('warehouse_id');
            $table->primary(['user_id', 'warehouse_id']);
        });

        Schema::create('refresh_tokens', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('user_id');
            $table->string('token_hash')->unique();
            $table->dateTime('expires_at', 3);
            $table->dateTime('revoked_at', 3)->nullable();
            $table->dateTime('created_at', 3)->useCurrent();
            $table->index(['user_id'], 'refresh_tokens_user_id_ix');
        });

        Schema::create('product_categories', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('code')->unique();
            $table->string('name_ar');
            $table->string('name_en');
            $table->ulid('parent_id')->nullable();
            $table->boolean('active')->default(true);
        });

        Schema::create('uoms', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('code')->unique();
            $table->string('name_ar');
            $table->string('name_en');
        });

        Schema::create('products', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('sku')->unique();
            $table->string('name_ar');
            $table->string('name_en');
            $table->string('brand')->nullable();
            $table->ulid('category_id')->nullable();
            $table->ulid('base_uom_id')->nullable();
            $table->string('storage_class', 40)->default('ambient');
            $table->double('weight_kg')->default(0);
            $table->integer('units_per_pallet')->nullable();
            $table->decimal('purchase_price', 14, 2)->nullable();
            $table->boolean('tracks_expiry')->default(false);
            $table->integer('reorder_min')->default(0);
            $table->integer('reorder_max')->nullable();
            $table->double('length_cm')->nullable();
            $table->double('width_cm')->nullable();
            $table->double('height_cm')->nullable();
            $table->double('volume_m3')->nullable();
            $table->integer('shelf_life_days')->nullable();
            $table->ulid('home_warehouse_id')->nullable();
            $table->string('preferred_supplier_name')->nullable();
            $table->boolean('active')->default(true);
            $table->timestamps(3);
            $table->index(['category_id'], 'products_category_id_ix');
            $table->index(['name_ar'], 'products_name_ar_ix');
        });

        Schema::create('product_barcodes', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('product_id');
            $table->string('barcode')->unique();
            $table->ulid('uom_id')->nullable();
            $table->boolean('is_primary')->default(false);
            $table->index(['product_id'], 'product_barcodes_product_id_ix');
        });

        Schema::create('product_suppliers', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('product_id');
            $table->ulid('supplier_id');
            $table->string('supplier_sku')->nullable();
            $table->decimal('price', 14, 2)->nullable();
            $table->integer('lead_days')->nullable();
            $table->boolean('preferred')->default(false);
            $table->unique(['product_id', 'supplier_id'], 'product_suppliers_product_id_supplier_id_uq');
        });

        Schema::create('product_storage_requirements', function (Blueprint $table) {
            $table->ulid('product_id')->primary();
            $table->string('storage_class', 40);
            $table->double('min_temp_c')->nullable();
            $table->double('max_temp_c')->nullable();
            $table->boolean('hazmat')->default(false);
            $table->text('notes')->nullable();
        });

        Schema::create('warehouses', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('code')->unique();
            $table->string('name_ar');
            $table->string('name_en');
            $table->string('city')->nullable();
            $table->string('type')->default('dc');
            $table->double('area_m2')->nullable();
            $table->integer('docks')->default(0);
            $table->string('temp_zones')->default('all');
            $table->string('hours')->nullable();
            $table->dateTime('open_date', 3)->nullable();
            $table->boolean('active')->default(true);
            $table->dateTime('created_at', 3)->useCurrent();
        });

        Schema::create('zones', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('warehouse_id');
            $table->string('code');
            $table->string('name_ar');
            $table->string('name_en');
            $table->string('type', 40)->default('ambient');
            $table->string('pick_strategy')->default('fefo');
            $table->double('min_temp_c')->nullable();
            $table->double('max_temp_c')->nullable();
            $table->integer('capacity_units')->nullable();
            $table->double('max_kg')->nullable();
            $table->boolean('active')->default(true);
            $table->unique(['warehouse_id', 'code'], 'zones_warehouse_id_code_uq');
        });

        Schema::create('racks', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('zone_id');
            $table->integer('aisle');
            $table->integer('rack_no');
            $table->string('code');
            $table->integer('levels')->default(1);
            $table->boolean('active')->default(true);
            $table->unique(['zone_id', 'code'], 'racks_zone_id_code_uq');
        });

        Schema::create('bins', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('warehouse_id');
            $table->ulid('zone_id');
            $table->ulid('rack_id')->nullable();
            $table->string('code');
            $table->integer('shelf_no')->nullable();
            $table->string('type')->default('shelf');
            $table->integer('capacity_units')->nullable();
            $table->double('max_kg')->nullable();
            $table->string('status', 40)->default('active');
            $table->ulid('fixed_product_id')->nullable();
            $table->unique(['warehouse_id', 'code'], 'bins_warehouse_id_code_uq');
            $table->index(['zone_id'], 'bins_zone_id_ix');
        });

        Schema::create('suppliers', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('code')->unique();
            $table->string('name_ar');
            $table->string('name_en');
            $table->string('category')->nullable();
            $table->string('category_en')->nullable();
            $table->integer('lead_days')->default(5);
            $table->double('otif')->default(0);
            $table->double('fill_rate')->default(0);
            $table->double('score')->default(70);
            $table->integer('orders_count')->default(0);
            $table->decimal('total_value', 16, 2)->default(0);
            $table->string('cr')->nullable();
            $table->string('vat')->nullable();
            $table->string('contact')->nullable();
            $table->string('email')->nullable();
            $table->string('terms')->nullable();
            $table->string('iban')->nullable();
            $table->decimal('min_order', 14, 2)->nullable();
            $table->text('notes')->nullable();
            $table->boolean('is_new')->default(false);
            $table->boolean('active')->default(true);
            $table->dateTime('created_at', 3)->useCurrent();
        });

        Schema::create('customers', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('code')->unique();
            $table->string('name_ar');
            $table->string('name_en');
            $table->string('city')->nullable();
            $table->string('zone')->nullable();
            $table->string('terms')->nullable();
            $table->decimal('credit_limit', 14, 2)->default(0);
            $table->decimal('balance', 14, 2)->default(0);
            $table->string('contact')->nullable();
            $table->string('price_list')->nullable();
            $table->text('address')->nullable();
            $table->double('lat')->nullable();
            $table->double('lng')->nullable();
            $table->boolean('active')->default(true);
            $table->dateTime('created_at', 3)->useCurrent();
        });

        Schema::create('purchase_requisitions', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('warehouse_id');
            $table->string('requested_by_id')->nullable();
            $table->string('requested_by')->nullable();
            $table->dateTime('need_date', 3)->nullable();
            $table->string('priority')->default('normal');
            $table->text('justification')->nullable();
            $table->string('cost_center')->nullable();
            $table->string('status')->default('draft');
            $table->dateTime('submitted_at', 3)->nullable();
            $table->dateTime('approved_at', 3)->nullable();
            $table->string('rfq_id')->nullable();
            $table->string('po_id')->nullable();
            $table->timestamps(3);
        });

        Schema::create('pr_lines', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('pr_id');
            $table->integer('line_no');
            $table->ulid('product_id');
            $table->integer('qty');
            $table->decimal('est_price', 14, 2)->nullable();
            $table->text('notes')->nullable();
            $table->unique(['pr_id', 'line_no'], 'pr_lines_pr_id_line_no_uq');
        });

        Schema::create('pr_approvals', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('pr_id');
            $table->integer('step');
            $table->string('role_key');
            $table->string('approver_id')->nullable();
            $table->string('approver')->nullable();
            $table->string('decision')->default('pending');
            $table->text('note')->nullable();
            $table->dateTime('decided_at', 3)->nullable();
            $table->unique(['pr_id', 'step'], 'pr_approvals_pr_id_step_uq');
        });

        Schema::create('rfqs', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('pr_id')->nullable();
            $table->dateTime('close_date', 3)->nullable();
            $table->string('invited_rule')->nullable();
            $table->string('terms')->nullable();
            $table->ulid('delivery_warehouse_id')->nullable();
            $table->text('notes')->nullable();
            $table->string('status')->default('open');
            $table->ulid('awarded_quotation_id')->nullable()->unique();
            $table->dateTime('awarded_at', 3)->nullable();
            $table->dateTime('created_at', 3)->useCurrent();
        });

        Schema::create('rfq_lines', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('rfq_id');
            $table->integer('line_no');
            $table->ulid('product_id');
            $table->integer('qty');
            $table->unique(['rfq_id', 'line_no'], 'rfq_lines_rfq_id_line_no_uq');
        });

        Schema::create('rfq_suppliers', function (Blueprint $table) {
            $table->ulid('rfq_id');
            $table->ulid('supplier_id');
            $table->dateTime('invited_at', 3)->useCurrent();
            $table->primary(['rfq_id', 'supplier_id']);
        });

        Schema::create('supplier_quotations', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('supplier_id');
            $table->ulid('rfq_id')->nullable();
            $table->string('supplier_ref')->nullable();
            $table->dateTime('date', 3)->useCurrent();
            $table->dateTime('valid_until', 3)->nullable();
            $table->string('payment_terms')->nullable();
            $table->string('delivery_terms')->nullable();
            $table->integer('min_order')->default(0);
            $table->integer('lead_days')->default(0);
            $table->text('notes')->nullable();
            $table->string('attachment_name')->nullable();
            $table->string('attachment_type')->nullable();
            $table->boolean('recommended')->default(false);
            $table->double('score')->nullable();
            $table->string('status')->default('received');
            $table->dateTime('created_at', 3)->useCurrent();
        });

        Schema::create('supplier_quotation_lines', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('quotation_id');
            $table->ulid('product_id');
            $table->integer('qty')->nullable();
            $table->decimal('price', 14, 2);
            $table->double('vat_pct')->default(15);
            $table->integer('lead_days')->nullable();
        });

        Schema::create('purchase_orders', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('supplier_id');
            $table->ulid('warehouse_id');
            $table->ulid('rfq_id')->nullable();
            $table->string('status')->default('pending');
            $table->decimal('total', 16, 2)->default(0);
            $table->dateTime('due_date', 3)->nullable();
            $table->string('payment_terms')->nullable();
            $table->string('reference')->nullable();
            $table->text('notes')->nullable();
            $table->integer('approval_step')->default(0);
            $table->integer('open_qty')->default(0);
            $table->string('created_by_id')->nullable();
            $table->string('created_by')->nullable();
            $table->dateTime('approved_at', 3)->nullable();
            $table->dateTime('sent_at', 3)->nullable();
            $table->dateTime('confirmed_at', 3)->nullable();
            $table->dateTime('closed_at', 3)->nullable();
            $table->timestamps(3);
            $table->index(['status'], 'purchase_orders_status_ix');
        });

        Schema::create('po_lines', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('po_id');
            $table->integer('line_no');
            $table->ulid('product_id');
            $table->integer('qty');
            $table->decimal('price', 14, 2);
            $table->integer('received_qty')->default(0);
            $table->integer('damaged_qty')->default(0);
            $table->integer('rejected_qty')->default(0);
            $table->unique(['po_id', 'line_no'], 'po_lines_po_id_line_no_uq');
        });

        Schema::create('po_approvals', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('po_id');
            $table->integer('step');
            $table->string('role_key');
            $table->string('label_ar');
            $table->string('label_en');
            $table->string('approver_id')->nullable();
            $table->string('approver')->nullable();
            $table->string('decision')->default('pending');
            $table->text('note')->nullable();
            $table->dateTime('decided_at', 3)->nullable();
            $table->unique(['po_id', 'step'], 'po_approvals_po_id_step_uq');
        });

        Schema::create('inbound_shipments', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('po_id');
            $table->ulid('supplier_id');
            $table->ulid('warehouse_id');
            $table->dateTime('eta', 3)->nullable();
            $table->string('status')->default('expected');
            $table->dateTime('arrived_at', 3)->nullable();
            $table->dateTime('inspection_started_at', 3)->nullable();
            $table->dateTime('completed_at', 3)->nullable();
            $table->boolean('locked')->default(false);
            $table->string('carrier')->nullable();
            $table->text('notes')->nullable();
            $table->timestamps(3);
            $table->index(['status'], 'inbound_shipments_status_ix');
        });

        Schema::create('shipment_lines', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('shipment_id');
            $table->integer('line_no');
            $table->ulid('po_line_id')->nullable();
            $table->ulid('product_id');
            $table->integer('ordered_qty');
            $table->integer('accepted_qty')->default(0);
            $table->integer('damaged_qty')->default(0);
            $table->integer('rejected_qty')->default(0);
            $table->string('batch_no')->nullable();
            $table->dateTime('mfg_date', 3)->nullable();
            $table->dateTime('expiry_date', 3)->nullable();
            $table->ulid('suggested_bin_id')->nullable();
            $table->string('suggestion_ar')->nullable();
            $table->string('suggestion_en')->nullable();
            $table->unique(['shipment_id', 'line_no'], 'shipment_lines_shipment_id_line_no_uq');
        });

        Schema::create('goods_receipts', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('shipment_id');
            $table->ulid('po_id');
            $table->ulid('supplier_id');
            $table->ulid('warehouse_id');
            $table->string('posted_by_id')->nullable();
            $table->string('posted_by')->nullable();
            $table->dateTime('posted_at', 3)->useCurrent();
            $table->string('summary_ar')->nullable();
            $table->string('summary_en')->nullable();
            $table->string('transaction_id')->nullable();
        });

        Schema::create('grn_lines', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('grn_id');
            $table->integer('line_no');
            $table->ulid('shipment_line_id')->nullable();
            $table->ulid('po_line_id')->nullable();
            $table->ulid('product_id');
            $table->integer('received_qty');
            $table->integer('accepted_qty');
            $table->integer('damaged_qty')->default(0);
            $table->integer('rejected_qty')->default(0);
            $table->integer('remaining_qty')->default(0);
            $table->string('batch_no')->nullable();
            $table->ulid('batch_id')->nullable();
            $table->dateTime('mfg_date', 3)->nullable();
            $table->dateTime('expiry_date', 3)->nullable();
            $table->string('qc_result')->default('accepted');
            $table->text('qc_note')->nullable();
            $table->string('qc_by_id')->nullable();
            $table->dateTime('qc_at', 3)->nullable();
            $table->unique(['grn_id', 'line_no'], 'grn_lines_grn_id_line_no_uq');
        });

        Schema::create('qc_results', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('grn_line_id');
            $table->string('result');
            $table->integer('qty');
            $table->string('inspector_id')->nullable();
            $table->string('inspector')->nullable();
            $table->text('notes')->nullable();
            $table->dateTime('at', 3)->useCurrent();
        });

        Schema::create('putaway_tasks', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('grn_id');
            $table->ulid('grn_line_id');
            $table->ulid('shipment_id')->nullable();
            $table->ulid('product_id');
            $table->ulid('batch_id')->nullable();
            $table->string('batch_no')->nullable();
            $table->dateTime('expiry_date', 3)->nullable();
            $table->integer('qty');
            $table->ulid('warehouse_id');
            $table->ulid('suggested_bin_id')->nullable();
            $table->string('suggestion_ar')->nullable();
            $table->string('suggestion_en')->nullable();
            $table->ulid('actual_bin_id')->nullable();
            $table->string('status')->default('open');
            $table->string('confirmed_by_id')->nullable();
            $table->string('confirmed_by')->nullable();
            $table->dateTime('confirmed_at', 3)->nullable();
            $table->dateTime('created_at', 3)->useCurrent();
            $table->index(['status'], 'putaway_tasks_status_ix');
        });

        Schema::create('batches', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('product_id');
            $table->string('batch_no');
            $table->dateTime('mfg_date', 3)->nullable();
            $table->dateTime('expiry_date', 3)->nullable();
            $table->ulid('supplier_id')->nullable();
            $table->dateTime('created_at', 3)->useCurrent();
            $table->unique(['product_id', 'batch_no'], 'batches_product_id_batch_no_uq');
        });

        Schema::create('inventory_balances', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('product_id');
            $table->ulid('warehouse_id');
            $table->ulid('bin_id');
            $table->ulid('batch_id')->nullable();
            $table->string('batch_key')->default('');
            $table->integer('on_hand')->default(0);
            $table->integer('reserved')->default(0);
            $table->integer('allocated')->default(0);
            $table->boolean('quarantine')->default(false);
            $table->boolean('blocked')->default(false);
            $table->integer('version')->default(0);
            $table->dateTime('updated_at', 3);
            $table->unique(['product_id', 'bin_id', 'batch_key'], 'inventory_balances_product_id_bin_id_batch_key_uq');
            $table->index(['warehouse_id', 'product_id'], 'inventory_balances_warehouse_id_product_id_ix');
        });

        Schema::create('inventory_movements', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->string('type', 40);
            $table->ulid('product_id');
            $table->ulid('batch_id')->nullable();
            $table->string('batch_no')->nullable();
            $table->integer('qty');
            $table->integer('before_qty')->nullable();
            $table->integer('after_qty')->nullable();
            $table->string('src_warehouse_id')->nullable();
            $table->string('src_zone_id')->nullable();
            $table->string('src_rack_id')->nullable();
            $table->ulid('src_bin_id')->nullable();
            $table->string('dst_warehouse_id')->nullable();
            $table->string('dst_zone_id')->nullable();
            $table->string('dst_rack_id')->nullable();
            $table->ulid('dst_bin_id')->nullable();
            $table->string('reference_type')->nullable();
            $table->string('reference_id')->nullable();
            $table->string('reference_number')->nullable();
            $table->text('note')->nullable();
            $table->string('user_id')->nullable();
            $table->string('username')->nullable();
            $table->string('transaction_id')->nullable();
            $table->dateTime('created_at', 3)->useCurrent();
            $table->index(['product_id', 'created_at'], 'inventory_movements_product_id_created_at_ix');
            $table->index(['reference_type', 'reference_id'], 'inventory_movements_reference_type_reference_id_ix');
            $table->index(['transaction_id'], 'inventory_movements_transaction_id_ix');
        });

        Schema::create('inventory_reservations', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('so_id');
            $table->ulid('so_line_id');
            $table->ulid('product_id');
            $table->ulid('warehouse_id');
            $table->integer('qty');
            $table->string('status')->default('active');
            $table->dateTime('created_at', 3)->useCurrent();
            $table->dateTime('released_at', 3)->nullable();
            $table->index(['so_id'], 'inventory_reservations_so_id_ix');
        });

        Schema::create('inventory_allocations', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('reservation_id');
            $table->ulid('so_line_id');
            $table->ulid('product_id');
            $table->ulid('warehouse_id');
            $table->ulid('bin_id');
            $table->ulid('batch_id')->nullable();
            $table->integer('qty');
            $table->integer('picked_qty')->default(0);
            $table->string('status')->default('active');
            $table->dateTime('created_at', 3)->useCurrent();
            $table->index(['so_line_id'], 'inventory_allocations_so_line_id_ix');
        });

        Schema::create('warehouse_transfers', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('from_warehouse_id');
            $table->ulid('to_warehouse_id');
            $table->string('status')->default('draft');
            $table->string('reason_code')->nullable();
            $table->string('reason_ar')->nullable();
            $table->string('reason_en')->nullable();
            $table->text('notes')->nullable();
            $table->string('requested_by_id')->nullable();
            $table->string('requested_by')->nullable();
            $table->dateTime('date', 3)->nullable();
            $table->dateTime('eta', 3)->nullable();
            $table->string('approved_by_id')->nullable();
            $table->dateTime('approved_at', 3)->nullable();
            $table->dateTime('shipped_at', 3)->nullable();
            $table->dateTime('received_at', 3)->nullable();
            $table->dateTime('closed_at', 3)->nullable();
            $table->timestamps(3);
        });

        Schema::create('transfer_lines', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('transfer_id');
            $table->integer('line_no');
            $table->ulid('product_id');
            $table->ulid('batch_id')->nullable();
            $table->string('batch_no')->nullable();
            $table->integer('qty');
            $table->ulid('from_bin_id');
            $table->ulid('to_bin_id')->nullable();
            $table->integer('received_qty')->nullable();
            $table->unique(['transfer_id', 'line_no'], 'transfer_lines_transfer_id_line_no_uq');
        });

        Schema::create('inventory_counts', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('warehouse_id');
            $table->ulid('zone_id')->nullable();
            $table->string('type')->default('cycle');
            $table->string('scope')->nullable();
            $table->boolean('blind')->default(true);
            $table->boolean('freeze')->default(true);
            $table->string('status')->default('open');
            $table->string('counter_id')->nullable();
            $table->string('counter')->nullable();
            $table->dateTime('date', 3)->nullable();
            $table->string('approved_by_id')->nullable();
            $table->dateTime('adjusted_at', 3)->nullable();
            $table->dateTime('created_at', 3)->useCurrent();
        });

        Schema::create('count_lines', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('count_id');
            $table->ulid('product_id');
            $table->ulid('bin_id');
            $table->ulid('batch_id')->nullable();
            $table->integer('system_qty');
            $table->integer('counted_qty')->nullable();
        });

        Schema::create('staging_entries', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('direction');
            $table->ulid('bin_id');
            $table->string('reference_type');
            $table->string('reference_id');
            $table->string('reference_number')->nullable();
            $table->integer('qty')->nullable();
            $table->string('status')->default('waiting');
            $table->dateTime('created_at', 3)->useCurrent();
            $table->dateTime('cleared_at', 3)->nullable();
            $table->index(['reference_type', 'reference_id'], 'staging_entries_reference_type_reference_id_ix');
        });

        Schema::create('quotations', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('customer_id');
            $table->dateTime('date', 3)->useCurrent();
            $table->dateTime('valid_until', 3)->nullable();
            $table->string('status')->default('draft');
            $table->string('terms')->nullable();
            $table->string('delivery')->nullable();
            $table->text('notes')->nullable();
            $table->string('created_by_id')->nullable();
            $table->string('created_by')->nullable();
            $table->ulid('so_id')->nullable()->unique();
            $table->json('attachments');
            $table->timestamps(3);
        });

        Schema::create('quotation_lines', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('quotation_id');
            $table->integer('line_no');
            $table->ulid('product_id');
            $table->integer('qty');
            $table->decimal('price', 14, 2);
            $table->double('disc_pct')->default(0);
            $table->unique(['quotation_id', 'line_no'], 'quotation_lines_quotation_id_line_no_uq');
        });

        Schema::create('sales_orders', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('customer_id');
            $table->ulid('warehouse_id');
            $table->dateTime('date', 3)->useCurrent();
            $table->dateTime('due_date', 3)->nullable();
            $table->string('window')->nullable();
            $table->string('priority')->default('normal');
            $table->string('status')->default('confirmed');
            $table->double('kg')->default(0);
            $table->double('cbm')->default(0);
            $table->ulid('consolidation_id')->nullable();
            $table->string('trip_id')->nullable();
            $table->string('created_by_id')->nullable();
            $table->string('created_by')->nullable();
            $table->timestamps(3);
            $table->index(['status'], 'sales_orders_status_ix');
        });

        Schema::create('sales_order_lines', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('so_id');
            $table->integer('line_no');
            $table->ulid('product_id');
            $table->integer('qty');
            $table->decimal('price', 14, 2);
            $table->double('disc_pct')->default(0);
            $table->integer('reserved_qty')->default(0);
            $table->integer('allocated_qty')->default(0);
            $table->integer('picked_qty')->default(0);
            $table->integer('delivered_qty')->default(0);
            $table->integer('returned_qty')->default(0);
            $table->unique(['so_id', 'line_no'], 'sales_order_lines_so_id_line_no_uq');
        });

        Schema::create('order_consolidations', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('warehouse_id');
            $table->string('rule')->nullable();
            $table->string('status')->default('open');
            $table->string('created_by_id')->nullable();
            $table->string('created_by')->nullable();
            $table->string('trip_id')->nullable();
            $table->timestamps(3);
        });

        Schema::create('fulfillment_orders', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('so_id')->nullable();
            $table->ulid('customer_id');
            $table->ulid('warehouse_id');
            $table->string('status')->default('alloc');
            $table->integer('seq')->default(0);
            $table->integer('cartons')->default(0);
            $table->double('weight_kg')->default(0);
            $table->double('cbm')->default(0);
            $table->string('zone_ar')->nullable();
            $table->string('zone_en')->nullable();
            $table->ulid('trip_id')->nullable();
            $table->boolean('loaded')->default(false);
            $table->dateTime('loaded_at', 3)->nullable();
            $table->dateTime('packed_at', 3)->nullable();
            $table->dateTime('staged_at', 3)->nullable();
            $table->dateTime('dispatched_at', 3)->nullable();
            $table->dateTime('delivered_at', 3)->nullable();
            $table->timestamps(3);
            $table->index(['status'], 'fulfillment_orders_status_ix');
        });

        Schema::create('fo_lines', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('fo_id');
            $table->integer('line_no');
            $table->ulid('so_line_id')->nullable();
            $table->ulid('product_id');
            $table->integer('qty');
            $table->integer('picked_qty')->default(0);
            $table->integer('packed_qty')->default(0);
            $table->integer('delivered_qty')->default(0);
            $table->integer('returned_qty')->default(0);
            $table->unique(['fo_id', 'line_no'], 'fo_lines_fo_id_line_no_uq');
        });

        Schema::create('pick_lists', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('warehouse_id');
            $table->ulid('fo_id')->nullable();
            $table->string('status')->default('open');
            $table->string('assigned_to_id')->nullable();
            $table->string('assigned_to')->nullable();
            $table->dateTime('created_at', 3)->useCurrent();
            $table->dateTime('completed_at', 3)->nullable();
        });

        Schema::create('pick_tasks', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('pick_list_id');
            $table->ulid('fo_line_id');
            $table->integer('seq')->default(0);
            $table->ulid('product_id');
            $table->ulid('bin_id');
            $table->ulid('batch_id')->nullable();
            $table->string('batch_no')->nullable();
            $table->integer('qty');
            $table->integer('picked_qty')->default(0);
            $table->string('status')->default('open');
            $table->string('picked_by_id')->nullable();
            $table->string('picked_by')->nullable();
            $table->dateTime('picked_at', 3)->nullable();
        });

        Schema::create('packages', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('fo_id');
            $table->integer('cartons')->default(1);
            $table->double('weight_kg')->nullable();
            $table->double('volume_m3')->nullable();
            $table->string('label_ref')->nullable();
            $table->string('packed_by_id')->nullable();
            $table->string('packed_by')->nullable();
            $table->dateTime('packed_at', 3)->useCurrent();
        });

        Schema::create('vehicles', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('code')->unique();
            $table->string('plate_ar');
            $table->string('plate_en')->nullable();
            $table->string('brand')->nullable();
            $table->string('model')->nullable();
            $table->integer('year')->nullable();
            $table->string('vin')->nullable();
            $table->string('ownership')->default('owned');
            $table->string('kind')->default('dry');
            $table->string('type_ar')->nullable();
            $table->string('type_en')->nullable();
            $table->string('temp_range')->nullable();
            $table->double('max_kg')->default(0);
            $table->double('max_cbm')->default(0);
            $table->integer('pallets')->default(0);
            $table->integer('compartments')->default(1);
            $table->integer('odometer')->default(0);
            $table->integer('engine_hours')->default(0);
            $table->string('fuel_type')->nullable();
            $table->integer('tank_l')->nullable();
            $table->double('avg_km_l')->default(6);
            $table->dateTime('reg_expiry', 3)->nullable();
            $table->dateTime('insurance_expiry', 3)->nullable();
            $table->dateTime('inspection_expiry', 3)->nullable();
            $table->dateTime('op_card_expiry', 3)->nullable();
            $table->dateTime('last_maint_date', 3)->nullable();
            $table->dateTime('next_maint_date', 3)->nullable();
            $table->integer('next_maint_km')->nullable();
            $table->string('gps_device_id')->nullable();
            $table->string('telematics_provider')->nullable();
            $table->boolean('gps_online')->default(false);
            $table->dateTime('last_sync_at', 3)->nullable();
            $table->ulid('warehouse_id')->nullable();
            $table->string('state')->default('available');
            $table->integer('fuel_pct')->nullable();
            $table->string('box_temp')->nullable();
            $table->double('map_x')->nullable();
            $table->double('map_y')->nullable();
            $table->double('lat')->nullable();
            $table->double('lng')->nullable();
            $table->boolean('active')->default(true);
            $table->timestamps(3);
        });

        Schema::create('drivers', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('code')->unique();
            $table->ulid('user_id')->nullable()->unique();
            $table->string('employee_no')->nullable();
            $table->string('name_ar');
            $table->string('name_en')->nullable();
            $table->string('nationality')->nullable();
            $table->string('mobile')->nullable();
            $table->string('license_no')->nullable();
            $table->string('license_type')->nullable();
            $table->dateTime('license_expiry', 3)->nullable();
            $table->dateTime('iqama_expiry', 3)->nullable();
            $table->dateTime('medical_expiry', 3)->nullable();
            $table->string('training')->nullable();
            $table->dateTime('join_date', 3)->nullable();
            $table->string('shift')->nullable();
            $table->string('shift_en')->nullable();
            $table->string('weekly_hours')->nullable();
            $table->dateTime('last_checkin', 3)->nullable();
            $table->ulid('default_vehicle_id')->nullable();
            $table->integer('trips')->default(0);
            $table->integer('deliveries')->default(0);
            $table->integer('fails')->default(0);
            $table->double('ok_pct')->default(100);
            $table->double('ontime_pct')->default(100);
            $table->string('avg_delay')->nullable();
            $table->integer('km')->default(0);
            $table->double('rating')->default(5);
            $table->integer('complaints')->default(0);
            $table->integer('incidents')->default(0);
            $table->double('fuel_score')->default(100);
            $table->double('safety')->default(100);
            $table->string('state')->default('available');
            $table->boolean('blocked')->default(false);
            $table->boolean('active')->default(true);
            $table->timestamps(3);
        });

        Schema::create('trips', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->dateTime('date', 3)->nullable();
            $table->ulid('warehouse_id');
            $table->ulid('vehicle_id')->nullable();
            $table->ulid('driver_id')->nullable();
            $table->string('route_ar')->nullable();
            $table->string('route_en')->nullable();
            $table->double('km')->default(0);
            $table->string('planned_start')->nullable();
            $table->dateTime('actual_start', 3)->nullable();
            $table->string('planned_end')->nullable();
            $table->dateTime('actual_end', 3)->nullable();
            $table->string('eta')->nullable();
            $table->integer('delay_min')->default(0);
            $table->string('status')->default('planned');
            $table->double('kg')->default(0);
            $table->double('cbm')->default(0);
            $table->integer('pallets')->default(0);
            $table->string('temp_need')->default('dry');
            $table->ulid('consolidation_id')->nullable();
            $table->string('created_by_id')->nullable();
            $table->string('created_by')->nullable();
            $table->dateTime('dispatched_at', 3)->nullable();
            $table->dateTime('closed_at', 3)->nullable();
            $table->timestamps(3);
            $table->index(['status'], 'trips_status_ix');
        });

        Schema::create('trip_stops', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('trip_id');
            $table->integer('seq');
            $table->ulid('customer_id')->nullable();
            $table->string('customer_ar');
            $table->string('customer_en')->nullable();
            $table->ulid('so_id')->nullable();
            $table->ulid('fo_id')->nullable();
            $table->string('invoice')->nullable();
            $table->integer('items')->default(0);
            $table->double('kg')->default(0);
            $table->string('window')->nullable();
            $table->string('contact')->nullable();
            $table->text('address')->nullable();
            $table->string('planned_time')->nullable();
            $table->string('actual_time')->nullable();
            $table->string('status')->default('pending');
            $table->text('fail_reason')->nullable();
            $table->text('note')->nullable();
            $table->double('map_x')->nullable();
            $table->double('map_y')->nullable();
            $table->dateTime('arrived_at', 3)->nullable();
            $table->dateTime('completed_at', 3)->nullable();
            $table->unique(['trip_id', 'seq'], 'trip_stops_trip_id_seq_uq');
        });

        Schema::create('trip_orders', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('trip_id');
            $table->ulid('fo_id');
            $table->ulid('stop_id')->nullable();
            $table->boolean('loaded')->default(false);
            $table->dateTime('loaded_at', 3)->nullable();
            $table->integer('load_seq')->nullable();
            $table->unique(['trip_id', 'fo_id'], 'trip_orders_trip_id_fo_id_uq');
        });

        Schema::create('trip_events', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('trip_id');
            $table->dateTime('at', 3)->useCurrent();
            $table->string('label')->nullable();
            $table->string('text_ar');
            $table->string('text_en')->nullable();
        });

        Schema::create('trip_costs', function (Blueprint $table) {
            $table->ulid('trip_id')->primary();
            $table->double('fuel')->default(0);
            $table->double('driver')->default(0);
            $table->double('ot')->default(0);
            $table->double('maint')->default(0);
            $table->double('dep')->default(0);
            $table->double('tolls')->default(0);
            $table->double('parking')->default(0);
            $table->double('third')->default(0);
            $table->double('other')->default(0);
        });

        Schema::create('loading_plans', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('trip_id');
            $table->ulid('vehicle_id');
            $table->string('status')->default('open');
            $table->double('total_kg')->default(0);
            $table->double('total_cbm')->default(0);
            $table->integer('total_pallets')->default(0);
            $table->dateTime('created_at', 3)->useCurrent();
            $table->dateTime('completed_at', 3)->nullable();
        });

        Schema::create('loading_lines', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('loading_plan_id');
            $table->ulid('fo_id');
            $table->integer('seq');
            $table->double('weight_kg')->default(0);
            $table->double('cbm')->default(0);
            $table->string('scanned_vehicle')->nullable();
            $table->string('scanned_order')->nullable();
            $table->string('status')->default('pending');
            $table->string('loaded_by_id')->nullable();
            $table->string('loaded_by')->nullable();
            $table->dateTime('loaded_at', 3)->nullable();
            $table->unique(['loading_plan_id', 'fo_id'], 'loading_lines_loading_plan_id_fo_id_uq');
        });

        Schema::create('dispatch_records', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('trip_id')->unique();
            $table->ulid('vehicle_id');
            $table->ulid('driver_id');
            $table->integer('orders_count');
            $table->double('total_kg')->default(0);
            $table->double('total_cbm')->default(0);
            $table->string('dispatched_by_id')->nullable();
            $table->string('dispatched_by')->nullable();
            $table->dateTime('dispatched_at', 3)->useCurrent();
        });

        Schema::create('routes', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('code')->unique();
            $table->string('name');
            $table->string('warehouse_id')->nullable();
            $table->string('zones')->nullable();
            $table->string('days')->nullable();
            $table->string('window')->nullable();
            $table->string('temp_need')->default('dry');
        });

        Schema::create('delivery_records', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('trip_id');
            $table->ulid('stop_id')->unique();
            $table->ulid('fo_id');
            $table->ulid('driver_id')->nullable();
            $table->ulid('vehicle_id')->nullable();
            $table->string('result');
            $table->integer('delivered_qty')->default(0);
            $table->integer('returned_qty')->default(0);
            $table->text('fail_reason')->nullable();
            $table->dateTime('arrived_at', 3)->nullable();
            $table->dateTime('completed_at', 3)->useCurrent();
        });

        Schema::create('proof_of_delivery', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('delivery_id')->nullable()->unique();
            $table->ulid('trip_id');
            $table->ulid('stop_id')->unique();
            $table->ulid('fo_id');
            $table->ulid('driver_id')->nullable();
            $table->ulid('vehicle_id')->nullable();
            $table->ulid('customer_id')->nullable();
            $table->string('result');
            $table->string('receiver_name')->nullable();
            $table->integer('delivered_qty')->nullable();
            $table->integer('returned_qty')->nullable();
            $table->double('gps_lat')->nullable();
            $table->double('gps_lng')->nullable();
            $table->double('gps_accuracy')->nullable();
            $table->string('gps_status')->default('unavailable');
            $table->text('notes')->nullable();
            $table->text('fail_reason')->nullable();
            $table->dateTime('at', 3)->useCurrent();
            $table->string('created_by_id')->nullable();
        });

        Schema::create('pod_attachments', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('pod_id');
            $table->string('kind');
            $table->string('file_name')->nullable();
            $table->string('mime')->nullable();
            $table->integer('size')->nullable();
            $table->string('storage_key')->nullable();
            $table->string('url')->nullable();
            $table->string('status')->default('integration_pending');
            $table->dateTime('created_at', 3)->useCurrent();
        });

        Schema::create('returns', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->string('type');
            $table->string('source_ar')->nullable();
            $table->string('source_en')->nullable();
            $table->string('reference')->nullable();
            $table->ulid('customer_id')->nullable();
            $table->ulid('supplier_id')->nullable();
            $table->ulid('fo_id')->nullable();
            $table->ulid('trip_id')->nullable();
            $table->ulid('warehouse_id');
            $table->string('status')->default('pending');
            $table->string('reason_code')->nullable();
            $table->string('reason_ar')->nullable();
            $table->string('reason_en')->nullable();
            $table->text('notes')->nullable();
            $table->json('attachments');
            $table->string('decision')->nullable();
            $table->string('decided_by_id')->nullable();
            $table->string('decided_by')->nullable();
            $table->dateTime('decided_at', 3)->nullable();
            $table->string('created_by_id')->nullable();
            $table->string('created_by')->nullable();
            $table->dateTime('approved_at', 3)->nullable();
            $table->dateTime('received_at', 3)->nullable();
            $table->dateTime('inspected_at', 3)->nullable();
            $table->dateTime('closed_at', 3)->nullable();
            $table->timestamps(3);
            $table->index(['status'], 'returns_status_ix');
        });

        Schema::create('return_lines', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('return_id');
            $table->integer('line_no');
            $table->ulid('product_id');
            $table->integer('qty');
            $table->string('batch_no')->nullable();
            $table->ulid('batch_id')->nullable();
            $table->ulid('bin_id')->nullable();
            $table->dateTime('expiry_date', 3)->nullable();
            $table->integer('inspected_qty')->nullable();
            $table->text('condition')->nullable();
            $table->string('decision')->nullable();
            $table->unique(['return_id', 'line_no'], 'return_lines_return_id_line_no_uq');
        });

        Schema::create('return_receiving', function (Blueprint $table) {
            $table->ulid('return_id')->primary();
            $table->string('received_by_id')->nullable();
            $table->string('received_by')->nullable();
            $table->dateTime('received_at', 3)->useCurrent();
            $table->string('bin_code')->nullable();
            $table->text('notes')->nullable();
        });

        Schema::create('return_inspections', function (Blueprint $table) {
            $table->ulid('return_id')->primary();
            $table->string('inspector_id')->nullable();
            $table->string('inspector')->nullable();
            $table->dateTime('started_at', 3)->useCurrent();
            $table->string('findings')->nullable();
        });

        Schema::create('return_decisions', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('return_id');
            $table->string('decision');
            $table->integer('qty');
            $table->string('target_bin_id')->nullable();
            $table->string('movement_id')->nullable();
            $table->string('decided_by_id')->nullable();
            $table->string('decided_by')->nullable();
            $table->text('note')->nullable();
            $table->dateTime('at', 3)->useCurrent();
        });

        Schema::create('maintenance_orders', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('vehicle_id');
            $table->string('type_ar')->nullable();
            $table->string('type_en')->nullable();
            $table->string('kind')->default('corrective');
            $table->string('desc_ar')->nullable();
            $table->string('desc_en')->nullable();
            $table->string('shop')->nullable();
            $table->dateTime('start_date', 3)->nullable();
            $table->dateTime('end_date', 3)->nullable();
            $table->integer('odometer')->nullable();
            $table->double('cost')->default(0);
            $table->double('parts')->default(0);
            $table->double('labor')->default(0);
            $table->integer('down_days')->nullable();
            $table->string('down_label')->nullable();
            $table->integer('next_km')->nullable();
            $table->string('status')->default('open');
            $table->dateTime('created_at', 3)->useCurrent();
        });

        Schema::create('fuel_records', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('vehicle_id');
            $table->ulid('driver_id')->nullable();
            $table->dateTime('date', 3);
            $table->integer('odometer');
            $table->double('liters');
            $table->double('cost');
            $table->string('station')->nullable();
            $table->boolean('full')->default(true);
            $table->double('km_per_l')->nullable();
            $table->double('cost_per_km')->nullable();
            $table->boolean('anomaly')->default(false);
            $table->string('receipt')->nullable();
            $table->dateTime('created_at', 3)->useCurrent();
        });

        Schema::create('fleet_alerts', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('code')->unique();
            $table->string('category');
            $table->string('severity')->default('w');
            $table->string('entity_type')->nullable();
            $table->string('entity_id')->nullable();
            $table->string('entity_code')->nullable();
            $table->string('text_ar');
            $table->string('text_en')->nullable();
            $table->string('due_date')->nullable();
            $table->string('owner')->nullable();
            $table->string('recommend_ar')->nullable();
            $table->string('recommend_en')->nullable();
            $table->string('status')->default('open');
            $table->dateTime('snoozed_until', 3)->nullable();
            $table->dateTime('resolved_at', 3)->nullable();
            $table->dateTime('created_at', 3)->useCurrent();
            $table->index(['status'], 'fleet_alerts_status_ix');
        });

        Schema::create('incidents', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('driver_id');
            $table->string('type');
            $table->dateTime('date', 3);
            $table->string('desc');
            $table->string('severity')->default('low');
            $table->dateTime('created_at', 3)->useCurrent();
        });

        Schema::create('ops_requests', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->string('type');
            $table->ulid('driver_id')->nullable();
            $table->string('driver_name')->nullable();
            $table->string('vehicle_code')->nullable();
            $table->string('trip_number')->nullable();
            $table->double('amount')->default(0);
            $table->string('desc');
            $table->string('location')->nullable();
            $table->string('attachment')->nullable();
            $table->string('status')->default('submitted');
            $table->dateTime('created_at', 3)->useCurrent();
        });

        Schema::create('dock_appointments', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->ulid('warehouse_id');
            $table->string('dock');
            $table->string('type');
            $table->string('reference');
            $table->dateTime('date', 3);
            $table->string('slot');
            $table->string('carrier')->nullable();
            $table->dateTime('created_at', 3)->useCurrent();
            $table->unique(['warehouse_id', 'dock', 'date', 'slot'], 'dock_appointments_warehouse_id_dock_date_slot_uq');
        });

        Schema::create('staff_assignments', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('warehouse_id');
            $table->string('who');
            $table->string('role');
            $table->string('zones')->nullable();
            $table->string('shift')->nullable();
            $table->dateTime('from_date', 3)->nullable();
            $table->string('cert')->nullable();
            $table->dateTime('created_at', 3)->useCurrent();
        });

        Schema::create('exceptions', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('number')->unique();
            $table->string('kind');
            $table->string('severity')->default('w');
            $table->string('status')->default('open');
            $table->string('owner_role')->nullable();
            $table->string('owner_user_id')->nullable();
            $table->double('sla_hours')->default(24);
            $table->string('entity_type')->nullable();
            $table->string('entity_id')->nullable();
            $table->string('entity_number')->nullable();
            $table->string('document_type')->nullable();
            $table->string('document_id')->nullable();
            $table->string('document_number')->nullable();
            $table->string('text_ar');
            $table->string('text_en')->nullable();
            $table->text('resolution')->nullable();
            $table->string('created_by_id')->nullable();
            $table->string('created_by')->nullable();
            $table->dateTime('created_at', 3)->useCurrent();
            $table->dateTime('acknowledged_at', 3)->nullable();
            $table->dateTime('resolved_at', 3)->nullable();
            $table->index(['status'], 'exceptions_status_ix');
            $table->index(['entity_type', 'entity_id'], 'exceptions_entity_type_entity_id_ix');
        });

        Schema::create('exception_events', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('exception_id');
            $table->string('from_status')->nullable();
            $table->string('to_status');
            $table->string('user_id')->nullable();
            $table->string('username')->nullable();
            $table->text('note')->nullable();
            $table->dateTime('at', 3)->useCurrent();
        });

        Schema::create('audit_logs', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->ulid('user_id')->nullable();
            $table->string('username')->nullable();
            $table->string('action');
            $table->string('entity_type');
            $table->string('entity_id')->nullable();
            $table->string('entity_number')->nullable();
            $table->string('field')->nullable();
            $table->string('old_value')->nullable();
            $table->string('new_value')->nullable();
            $table->string('request_id')->nullable();
            $table->string('transaction_id')->nullable();
            $table->string('ip')->nullable();
            $table->dateTime('at', 3)->useCurrent();
            $table->index(['entity_type', 'entity_id'], 'audit_logs_entity_type_entity_id_ix');
            $table->index(['at'], 'audit_logs_at_ix');
        });

        Schema::create('activity_logs', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('entity_type')->nullable();
            $table->string('entity_id')->nullable();
            $table->string('entity_number')->nullable();
            $table->string('text_ar');
            $table->string('text_en')->nullable();
            $table->string('user_id')->nullable();
            $table->string('username')->nullable();
            $table->dateTime('at', 3)->useCurrent();
            $table->index(['at'], 'activity_logs_at_ix');
        });

        Schema::create('notifications', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('role_key')->nullable();
            $table->string('user_id')->nullable();
            $table->string('text_ar');
            $table->string('text_en')->nullable();
            $table->string('entity_type')->nullable();
            $table->string('entity_id')->nullable();
            $table->string('entity_number')->nullable();
            $table->boolean('read')->default(false);
            $table->dateTime('at', 3)->useCurrent();
            $table->index(['role_key', 'read'], 'notifications_role_key_read_ix');
        });

        Schema::create('attachments', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('entity_type');
            $table->string('entity_id');
            $table->string('file_name');
            $table->string('mime')->nullable();
            $table->integer('size')->nullable();
            $table->string('storage_key')->nullable();
            $table->string('url')->nullable();
            $table->string('status')->default('integration_pending');
            $table->dateTime('created_at', 3)->useCurrent();
            $table->index(['entity_type', 'entity_id'], 'attachments_entity_type_entity_id_ix');
        });

        Schema::create('status_history', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('entity_type');
            $table->string('entity_id');
            $table->string('from_status')->nullable();
            $table->string('to_status');
            $table->string('user_id')->nullable();
            $table->string('username')->nullable();
            $table->text('note')->nullable();
            $table->dateTime('at', 3)->useCurrent();
            $table->index(['entity_type', 'entity_id'], 'status_history_entity_type_entity_id_ix');
        });

        Schema::create('system_settings', function (Blueprint $table) {
            $table->string('key')->primary();
            $table->json('value');
            $table->string('group')->default('general');
            $table->text('description')->nullable();
            $table->string('updated_by_id')->nullable();
            $table->dateTime('updated_at', 3);
        });

        Schema::create('number_sequences', function (Blueprint $table) {
            $table->string('key')->primary();
            $table->string('prefix');
            $table->integer('next')->default(1);
            $table->integer('width')->default(5);
        });

        Schema::create('idempotency_keys', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('user_id');
            $table->string('key');
            $table->string('route');
            $table->integer('response_status')->nullable();
            $table->json('response_body')->nullable();
            $table->dateTime('created_at', 3)->useCurrent();
            $table->unique(['user_id', 'key', 'route'], 'idempotency_keys_user_id_key_route_uq');
        });

        Schema::create('integration_events', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('type');
            $table->json('payload');
            $table->string('status')->default('pending');
            $table->integer('attempts')->default(0);
            $table->text('last_error')->nullable();
            $table->dateTime('created_at', 3)->useCurrent();
            $table->dateTime('sent_at', 3)->nullable();
            $table->index(['status'], 'integration_events_status_ix');
        });

    }

    public function down(): void
    {
        Schema::disableForeignKeyConstraints();
        Schema::dropIfExists('integration_events');
        Schema::dropIfExists('idempotency_keys');
        Schema::dropIfExists('number_sequences');
        Schema::dropIfExists('system_settings');
        Schema::dropIfExists('status_history');
        Schema::dropIfExists('attachments');
        Schema::dropIfExists('notifications');
        Schema::dropIfExists('activity_logs');
        Schema::dropIfExists('audit_logs');
        Schema::dropIfExists('exception_events');
        Schema::dropIfExists('exceptions');
        Schema::dropIfExists('staff_assignments');
        Schema::dropIfExists('dock_appointments');
        Schema::dropIfExists('ops_requests');
        Schema::dropIfExists('incidents');
        Schema::dropIfExists('fleet_alerts');
        Schema::dropIfExists('fuel_records');
        Schema::dropIfExists('maintenance_orders');
        Schema::dropIfExists('return_decisions');
        Schema::dropIfExists('return_inspections');
        Schema::dropIfExists('return_receiving');
        Schema::dropIfExists('return_lines');
        Schema::dropIfExists('returns');
        Schema::dropIfExists('pod_attachments');
        Schema::dropIfExists('proof_of_delivery');
        Schema::dropIfExists('delivery_records');
        Schema::dropIfExists('routes');
        Schema::dropIfExists('dispatch_records');
        Schema::dropIfExists('loading_lines');
        Schema::dropIfExists('loading_plans');
        Schema::dropIfExists('trip_costs');
        Schema::dropIfExists('trip_events');
        Schema::dropIfExists('trip_orders');
        Schema::dropIfExists('trip_stops');
        Schema::dropIfExists('trips');
        Schema::dropIfExists('drivers');
        Schema::dropIfExists('vehicles');
        Schema::dropIfExists('packages');
        Schema::dropIfExists('pick_tasks');
        Schema::dropIfExists('pick_lists');
        Schema::dropIfExists('fo_lines');
        Schema::dropIfExists('fulfillment_orders');
        Schema::dropIfExists('order_consolidations');
        Schema::dropIfExists('sales_order_lines');
        Schema::dropIfExists('sales_orders');
        Schema::dropIfExists('quotation_lines');
        Schema::dropIfExists('quotations');
        Schema::dropIfExists('staging_entries');
        Schema::dropIfExists('count_lines');
        Schema::dropIfExists('inventory_counts');
        Schema::dropIfExists('transfer_lines');
        Schema::dropIfExists('warehouse_transfers');
        Schema::dropIfExists('inventory_allocations');
        Schema::dropIfExists('inventory_reservations');
        Schema::dropIfExists('inventory_movements');
        Schema::dropIfExists('inventory_balances');
        Schema::dropIfExists('batches');
        Schema::dropIfExists('putaway_tasks');
        Schema::dropIfExists('qc_results');
        Schema::dropIfExists('grn_lines');
        Schema::dropIfExists('goods_receipts');
        Schema::dropIfExists('shipment_lines');
        Schema::dropIfExists('inbound_shipments');
        Schema::dropIfExists('po_approvals');
        Schema::dropIfExists('po_lines');
        Schema::dropIfExists('purchase_orders');
        Schema::dropIfExists('supplier_quotation_lines');
        Schema::dropIfExists('supplier_quotations');
        Schema::dropIfExists('rfq_suppliers');
        Schema::dropIfExists('rfq_lines');
        Schema::dropIfExists('rfqs');
        Schema::dropIfExists('pr_approvals');
        Schema::dropIfExists('pr_lines');
        Schema::dropIfExists('purchase_requisitions');
        Schema::dropIfExists('customers');
        Schema::dropIfExists('suppliers');
        Schema::dropIfExists('bins');
        Schema::dropIfExists('racks');
        Schema::dropIfExists('zones');
        Schema::dropIfExists('warehouses');
        Schema::dropIfExists('product_storage_requirements');
        Schema::dropIfExists('product_suppliers');
        Schema::dropIfExists('product_barcodes');
        Schema::dropIfExists('products');
        Schema::dropIfExists('uoms');
        Schema::dropIfExists('product_categories');
        Schema::dropIfExists('refresh_tokens');
        Schema::dropIfExists('user_warehouses');
        Schema::dropIfExists('role_permissions');
        Schema::dropIfExists('user_roles');
        Schema::dropIfExists('permissions');
        Schema::dropIfExists('roles');
        Schema::dropIfExists('users');
        Schema::enableForeignKeyConstraints();
    }
};
