// Status values, state machines, labels (with chip colours) and the permission catalogue.
// constants.json is generated from the same source as the server's config/scm.php, so both sides agree.
import constants from './constants.json';

export const {
  ROLE_LABELS, NAV_LABELS, MOVEMENT_LABELS, PO_LABELS, PR_LABELS, SHIPMENT_LABELS, QT_LABELS, SO_LABELS, OC_LABELS, FO_LABELS,
  TRIP_LABELS, STOP_LABELS, VEHICLE_LABELS, RETURN_LABELS, RETURN_DECISION_LABELS, TRANSFER_LABELS, EXCEPTION_STATE_LABELS,
  FAIL_REASON_LABELS, OWNERSHIP_LABELS, ALERT_CATEGORY_LABELS, DESIGN_TOKENS,
  PERMISSIONS, ROLE_PERMISSIONS, ROLE_NAV, ROLE_KEYS,
  STORAGE_CLASSES, ZONE_TYPES, PICK_STRATEGIES, BIN_TYPES, MOVEMENT_TYPES,
  PR_STATES, PR_TRANSITIONS, RFQ_STATES, PO_STATES, PO_TRANSITIONS, SHIPMENT_STATES, SHIPMENT_TRANSITIONS, QC_RESULTS,
  QUOTATION_STATES, QUOTATION_TRANSITIONS, SO_STATES, SO_TRANSITIONS, OC_STATES, OC_NEXT, FO_STATES, FO_TRANSITIONS, PICK_TASK_STATES,
  TRIP_STATES, TRIP_TRANSITIONS, STOP_STATES, STOP_TRANSITIONS, DELIVERY_RESULTS, FAIL_REASONS,
  VEHICLE_STATES, VEHICLE_TRANSITIONS, VEHICLE_KINDS, VEHICLE_OWNERSHIP, TEMP_NEEDS, DRIVER_STATES, MAINT_KINDS, MAINT_STATES,
  RETURN_TYPES, RETURN_STATES, RETURN_TRANSITIONS, RETURN_DECISIONS, RETURN_REASONS, TRANSFER_STATES, TRANSFER_TRANSITIONS,
  COUNT_STATES, EXCEPTION_KINDS, EXCEPTION_SEVERITIES, EXCEPTION_STATES, EXCEPTION_TRANSITIONS, ALERT_STATES, OPREQ_TYPES, OPREQ_STATES,
  INTEGRATION_STATUS,
} = constants;

export const ALL = constants;

/** The server decides; the client only uses this to show or hide buttons. */
export const canTransition = (table, from, to) => (table[from] || []).includes(to);
