<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;

class ActivityLog extends BaseModel
{
    use HasUlids;

    protected $table = 'activity_logs';

    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'at' => 'datetime',
        ];
    }
}
