<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;

class Attachment extends BaseModel
{
    use HasUlids;

    protected $table = 'attachments';
    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'size' => 'integer',
        ];
    }
}
