<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Batch extends BaseModel
{
    use HasUlids;

    protected $table = 'batches';

    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'mfg_date' => 'datetime',
            'expiry_date' => 'datetime',
        ];
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class, 'product_id', 'id');
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(Supplier::class, 'supplier_id', 'id');
    }

    public function balances(): HasMany
    {
        return $this->hasMany(InventoryBalance::class, 'batch_id', 'id');
    }

    public function movements(): HasMany
    {
        return $this->hasMany(InventoryMovement::class, 'batch_id', 'id');
    }

    public function grnLines(): HasMany
    {
        return $this->hasMany(GrnLine::class, 'batch_id', 'id');
    }

    public function putaways(): HasMany
    {
        return $this->hasMany(PutawayTask::class, 'batch_id', 'id');
    }

    public function allocations(): HasMany
    {
        return $this->hasMany(InventoryAllocation::class, 'batch_id', 'id');
    }

    public function pickTasks(): HasMany
    {
        return $this->hasMany(PickTask::class, 'batch_id', 'id');
    }

    public function transferLines(): HasMany
    {
        return $this->hasMany(TransferLine::class, 'batch_id', 'id');
    }

    public function countLines(): HasMany
    {
        return $this->hasMany(CountLine::class, 'batch_id', 'id');
    }

    public function returnLines(): HasMany
    {
        return $this->hasMany(ReturnLine::class, 'batch_id', 'id');
    }
}
