<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Customer extends BaseModel
{
    use HasUlids;

    protected $table = 'customers';
    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'credit_limit' => 'decimal:2',
            'balance' => 'decimal:2',
            'lat' => 'float',
            'lng' => 'float',
            'active' => 'boolean',
        ];
    }

    public function quotations(): HasMany
    {
        return $this->hasMany(\App\Models\Quotation::class, 'customer_id', 'id');
    }

    public function orders(): HasMany
    {
        return $this->hasMany(\App\Models\SalesOrder::class, 'customer_id', 'id');
    }

    public function fos(): HasMany
    {
        return $this->hasMany(\App\Models\FulfillmentOrder::class, 'customer_id', 'id');
    }

    public function stops(): HasMany
    {
        return $this->hasMany(\App\Models\TripStop::class, 'customer_id', 'id');
    }

    public function pods(): HasMany
    {
        return $this->hasMany(\App\Models\ProofOfDelivery::class, 'customer_id', 'id');
    }

    public function returns(): HasMany
    {
        return $this->hasMany(\App\Models\ReturnOrder::class, 'customer_id', 'id');
    }
}
