<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;

class DeliveryRecord extends BaseModel
{
    use HasUlids;

    protected $table = 'delivery_records';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'delivered_qty' => 'integer',
            'returned_qty' => 'integer',
            'arrived_at' => 'datetime',
            'completed_at' => 'datetime',
        ];
    }

    public function trip(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Trip::class, 'trip_id', 'id');
    }

    public function stop(): BelongsTo
    {
        return $this->belongsTo(\App\Models\TripStop::class, 'stop_id', 'id');
    }

    public function fo(): BelongsTo
    {
        return $this->belongsTo(\App\Models\FulfillmentOrder::class, 'fo_id', 'id');
    }

    public function driver(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Driver::class, 'driver_id', 'id');
    }

    public function vehicle(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Vehicle::class, 'vehicle_id', 'id');
    }

    public function pod(): HasOne
    {
        return $this->hasOne(\App\Models\ProofOfDelivery::class, 'delivery_id', 'id');
    }
}
