<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class DispatchRecord extends BaseModel
{
    use HasUlids;

    protected $table = 'dispatch_records';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'orders_count' => 'integer',
            'total_kg' => 'float',
            'total_cbm' => 'float',
            'dispatched_at' => 'datetime',
        ];
    }

    public function trip(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Trip::class, 'trip_id', 'id');
    }

    public function vehicle(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Vehicle::class, 'vehicle_id', 'id');
    }

    public function driver(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Driver::class, 'driver_id', 'id');
    }
}
