<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Driver extends BaseModel
{
    use HasUlids;

    protected $table = 'drivers';

    protected function casts(): array
    {
        return [
            'license_expiry' => 'datetime',
            'iqama_expiry' => 'datetime',
            'medical_expiry' => 'datetime',
            'join_date' => 'datetime',
            'last_checkin' => 'datetime',
            'trips' => 'integer',
            'deliveries' => 'integer',
            'fails' => 'integer',
            'ok_pct' => 'float',
            'ontime_pct' => 'float',
            'km' => 'integer',
            'rating' => 'float',
            'complaints' => 'integer',
            'incidents' => 'integer',
            'fuel_score' => 'float',
            'safety' => 'float',
            'blocked' => 'boolean',
            'active' => 'boolean',
            'phone_consent_at' => 'datetime',
            'phone_lat' => 'float',
            'phone_lng' => 'float',
            'phone_accuracy' => 'float',
            'phone_speed_kph' => 'float',
            'phone_at' => 'datetime',
        ];
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function defaultVehicle(): BelongsTo
    {
        return $this->belongsTo(Vehicle::class, 'default_vehicle_id', 'id');
    }

    public function tripsList(): HasMany
    {
        return $this->hasMany(Trip::class, 'driver_id', 'id');
    }

    public function fuel(): HasMany
    {
        return $this->hasMany(FuelRecord::class, 'driver_id', 'id');
    }

    public function dispatches(): HasMany
    {
        return $this->hasMany(DispatchRecord::class, 'driver_id', 'id');
    }

    public function pods(): HasMany
    {
        return $this->hasMany(ProofOfDelivery::class, 'driver_id', 'id');
    }

    public function deliveryRecords(): HasMany
    {
        return $this->hasMany(DeliveryRecord::class, 'driver_id', 'id');
    }

    public function incidentsList(): HasMany
    {
        return $this->hasMany(Incident::class, 'driver_id', 'id');
    }

    public function opsRequests(): HasMany
    {
        return $this->hasMany(OpsRequest::class, 'driver_id', 'id');
    }
}
