<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ExceptionEvent extends BaseModel
{
    use HasUlids;

    protected $table = 'exception_events';

    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'at' => 'datetime',
        ];
    }

    public function exception(): BelongsTo
    {
        return $this->belongsTo(OpsException::class, 'exception_id', 'id');
    }
}
