<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;

class FleetAlert extends BaseModel
{
    use HasUlids;

    protected $table = 'fleet_alerts';
    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'snoozed_until' => 'datetime',
            'resolved_at' => 'datetime',
        ];
    }
}
