<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class FoLine extends BaseModel
{
    use HasUlids;

    protected $table = 'fo_lines';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'line_no' => 'integer',
            'qty' => 'integer',
            'picked_qty' => 'integer',
            'packed_qty' => 'integer',
            'delivered_qty' => 'integer',
            'returned_qty' => 'integer',
        ];
    }

    public function fo(): BelongsTo
    {
        return $this->belongsTo(\App\Models\FulfillmentOrder::class, 'fo_id', 'id');
    }

    public function soLine(): BelongsTo
    {
        return $this->belongsTo(\App\Models\SalesOrderLine::class, 'so_line_id', 'id');
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Product::class, 'product_id', 'id');
    }

    public function pickTasks(): HasMany
    {
        return $this->hasMany(\App\Models\PickTask::class, 'fo_line_id', 'id');
    }
}
