<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class FuelRecord extends BaseModel
{
    use HasUlids;

    protected $table = 'fuel_records';
    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'date' => 'datetime',
            'odometer' => 'integer',
            'liters' => 'float',
            'cost' => 'float',
            'full' => 'boolean',
            'km_per_l' => 'float',
            'cost_per_km' => 'float',
            'anomaly' => 'boolean',
        ];
    }

    public function vehicle(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Vehicle::class, 'vehicle_id', 'id');
    }

    public function driver(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Driver::class, 'driver_id', 'id');
    }
}
