<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class FulfillmentOrder extends BaseModel
{
    use HasUlids;

    protected $table = 'fulfillment_orders';

    protected function casts(): array
    {
        return [
            'seq' => 'integer',
            'cartons' => 'integer',
            'weight_kg' => 'float',
            'cbm' => 'float',
            'loaded' => 'boolean',
            'loaded_at' => 'datetime',
            'packed_at' => 'datetime',
            'staged_at' => 'datetime',
            'dispatched_at' => 'datetime',
            'delivered_at' => 'datetime',
        ];
    }

    public function so(): BelongsTo
    {
        return $this->belongsTo(SalesOrder::class, 'so_id', 'id');
    }

    public function customer(): BelongsTo
    {
        return $this->belongsTo(Customer::class, 'customer_id', 'id');
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(Warehouse::class, 'warehouse_id', 'id');
    }

    public function trip(): BelongsTo
    {
        return $this->belongsTo(Trip::class, 'trip_id', 'id');
    }

    public function lines(): HasMany
    {
        return $this->hasMany(FoLine::class, 'fo_id', 'id');
    }

    public function pickLists(): HasMany
    {
        return $this->hasMany(PickList::class, 'fo_id', 'id');
    }

    public function packages(): HasMany
    {
        return $this->hasMany(Package::class, 'fo_id', 'id');
    }

    public function tripOrders(): HasMany
    {
        return $this->hasMany(TripOrder::class, 'fo_id', 'id');
    }

    public function loadingLines(): HasMany
    {
        return $this->hasMany(LoadingLine::class, 'fo_id', 'id');
    }

    public function stops(): HasMany
    {
        return $this->hasMany(TripStop::class, 'fo_id', 'id');
    }

    public function deliveries(): HasMany
    {
        return $this->hasMany(DeliveryRecord::class, 'fo_id', 'id');
    }

    public function pods(): HasMany
    {
        return $this->hasMany(ProofOfDelivery::class, 'fo_id', 'id');
    }

    public function returns(): HasMany
    {
        return $this->hasMany(ReturnOrder::class, 'fo_id', 'id');
    }
}
