<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class GrnLine extends BaseModel
{
    use HasUlids;

    protected $table = 'grn_lines';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'line_no' => 'integer',
            'received_qty' => 'integer',
            'accepted_qty' => 'integer',
            'damaged_qty' => 'integer',
            'rejected_qty' => 'integer',
            'remaining_qty' => 'integer',
            'mfg_date' => 'datetime',
            'expiry_date' => 'datetime',
            'qc_at' => 'datetime',
        ];
    }

    public function grn(): BelongsTo
    {
        return $this->belongsTo(\App\Models\GoodsReceipt::class, 'grn_id', 'id');
    }

    public function shipmentLine(): BelongsTo
    {
        return $this->belongsTo(\App\Models\ShipmentLine::class, 'shipment_line_id', 'id');
    }

    public function poLine(): BelongsTo
    {
        return $this->belongsTo(\App\Models\PoLine::class, 'po_line_id', 'id');
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Product::class, 'product_id', 'id');
    }

    public function batch(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Batch::class, 'batch_id', 'id');
    }

    public function qcResults(): HasMany
    {
        return $this->hasMany(\App\Models\QcResult::class, 'grn_line_id', 'id');
    }

    public function putaways(): HasMany
    {
        return $this->hasMany(\App\Models\PutawayTask::class, 'grn_line_id', 'id');
    }
}
