<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class InboundShipment extends BaseModel
{
    use HasUlids;

    protected $table = 'inbound_shipments';

    protected function casts(): array
    {
        return [
            'eta' => 'datetime',
            'arrived_at' => 'datetime',
            'inspection_started_at' => 'datetime',
            'completed_at' => 'datetime',
            'locked' => 'boolean',
        ];
    }

    public function po(): BelongsTo
    {
        return $this->belongsTo(\App\Models\PurchaseOrder::class, 'po_id', 'id');
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Supplier::class, 'supplier_id', 'id');
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Warehouse::class, 'warehouse_id', 'id');
    }

    public function lines(): HasMany
    {
        return $this->hasMany(\App\Models\ShipmentLine::class, 'shipment_id', 'id');
    }

    public function grns(): HasMany
    {
        return $this->hasMany(\App\Models\GoodsReceipt::class, 'shipment_id', 'id');
    }

    public function putaways(): HasMany
    {
        return $this->hasMany(\App\Models\PutawayTask::class, 'shipment_id', 'id');
    }
}
