<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class InventoryAllocation extends BaseModel
{
    use HasUlids;

    protected $table = 'inventory_allocations';
    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'qty' => 'integer',
            'picked_qty' => 'integer',
        ];
    }

    public function reservation(): BelongsTo
    {
        return $this->belongsTo(\App\Models\InventoryReservation::class, 'reservation_id', 'id');
    }

    public function soLine(): BelongsTo
    {
        return $this->belongsTo(\App\Models\SalesOrderLine::class, 'so_line_id', 'id');
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Product::class, 'product_id', 'id');
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Warehouse::class, 'warehouse_id', 'id');
    }

    public function bin(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Bin::class, 'bin_id', 'id');
    }

    public function batch(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Batch::class, 'batch_id', 'id');
    }
}
