<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class InventoryMovement extends BaseModel
{
    use HasUlids;

    protected $table = 'inventory_movements';

    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'qty' => 'integer',
            'before_qty' => 'integer',
            'after_qty' => 'integer',
        ];
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class, 'product_id', 'id');
    }

    public function batch(): BelongsTo
    {
        return $this->belongsTo(Batch::class, 'batch_id', 'id');
    }

    public function srcBin(): BelongsTo
    {
        return $this->belongsTo(Bin::class, 'src_bin_id', 'id');
    }

    public function dstBin(): BelongsTo
    {
        return $this->belongsTo(Bin::class, 'dst_bin_id', 'id');
    }
}
