<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class InventoryReservation extends BaseModel
{
    use HasUlids;

    protected $table = 'inventory_reservations';
    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'qty' => 'integer',
            'released_at' => 'datetime',
        ];
    }

    public function so(): BelongsTo
    {
        return $this->belongsTo(\App\Models\SalesOrder::class, 'so_id', 'id');
    }

    public function soLine(): BelongsTo
    {
        return $this->belongsTo(\App\Models\SalesOrderLine::class, 'so_line_id', 'id');
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Product::class, 'product_id', 'id');
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Warehouse::class, 'warehouse_id', 'id');
    }

    public function allocations(): HasMany
    {
        return $this->hasMany(\App\Models\InventoryAllocation::class, 'reservation_id', 'id');
    }
}
