<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class InventoryCount extends BaseModel
{
    use HasUlids;

    protected $table = 'inventory_counts';
    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'blind' => 'boolean',
            'freeze' => 'boolean',
            'date' => 'datetime',
            'adjusted_at' => 'datetime',
        ];
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Warehouse::class, 'warehouse_id', 'id');
    }

    public function zone(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Zone::class, 'zone_id', 'id');
    }

    public function lines(): HasMany
    {
        return $this->hasMany(\App\Models\CountLine::class, 'count_id', 'id');
    }
}
