<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class LoadingPlan extends BaseModel
{
    use HasUlids;

    protected $table = 'loading_plans';
    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'total_kg' => 'float',
            'total_cbm' => 'float',
            'total_pallets' => 'integer',
            'completed_at' => 'datetime',
        ];
    }

    public function trip(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Trip::class, 'trip_id', 'id');
    }

    public function vehicle(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Vehicle::class, 'vehicle_id', 'id');
    }

    public function lines(): HasMany
    {
        return $this->hasMany(\App\Models\LoadingLine::class, 'loading_plan_id', 'id');
    }
}
