<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class LoadingLine extends BaseModel
{
    use HasUlids;

    protected $table = 'loading_lines';

    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'seq' => 'integer',
            'weight_kg' => 'float',
            'cbm' => 'float',
            'loaded_at' => 'datetime',
        ];
    }

    public function plan(): BelongsTo
    {
        return $this->belongsTo(LoadingPlan::class, 'loading_plan_id', 'id');
    }

    public function fo(): BelongsTo
    {
        return $this->belongsTo(FulfillmentOrder::class, 'fo_id', 'id');
    }
}
