<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class MaintenanceOrder extends BaseModel
{
    use HasUlids;

    protected $table = 'maintenance_orders';

    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'start_date' => 'datetime',
            'end_date' => 'datetime',
            'odometer' => 'integer',
            'cost' => 'float',
            'parts' => 'float',
            'labor' => 'float',
            'down_days' => 'integer',
            'next_km' => 'integer',
        ];
    }

    public function vehicle(): BelongsTo
    {
        return $this->belongsTo(Vehicle::class, 'vehicle_id', 'id');
    }
}
