<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

class NumberSequence extends BaseModel
{
    protected $table = 'number_sequences';

    protected $primaryKey = 'key';

    public $incrementing = false;

    protected $keyType = 'string';

    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'next' => 'integer',
            'width' => 'integer',
        ];
    }
}
