<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\HasMany;

class OpsException extends BaseModel
{
    use HasUlids;

    protected $table = 'exceptions';

    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'sla_hours' => 'float',
            'acknowledged_at' => 'datetime',
            'resolved_at' => 'datetime',
        ];
    }

    public function events(): HasMany
    {
        return $this->hasMany(ExceptionEvent::class, 'exception_id', 'id');
    }
}
