<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class OpsRequest extends BaseModel
{
    use HasUlids;

    protected $table = 'ops_requests';

    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'amount' => 'float',
        ];
    }

    public function driver(): BelongsTo
    {
        return $this->belongsTo(Driver::class, 'driver_id', 'id');
    }
}
