<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class OrderConsolidation extends BaseModel
{
    use HasUlids;

    protected $table = 'order_consolidations';

    protected function casts(): array
    {
        return [];
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(Warehouse::class, 'warehouse_id', 'id');
    }

    public function orders(): HasMany
    {
        return $this->hasMany(SalesOrder::class, 'consolidation_id', 'id');
    }

    public function trips(): HasMany
    {
        return $this->hasMany(Trip::class, 'consolidation_id', 'id');
    }
}
