<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Package extends BaseModel
{
    use HasUlids;

    protected $table = 'packages';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'cartons' => 'integer',
            'weight_kg' => 'float',
            'volume_m3' => 'float',
            'packed_at' => 'datetime',
        ];
    }

    public function fo(): BelongsTo
    {
        return $this->belongsTo(\App\Models\FulfillmentOrder::class, 'fo_id', 'id');
    }
}
