<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Permission extends BaseModel
{
    use HasUlids;

    protected $table = 'permissions';

    public $timestamps = false;

    protected function casts(): array
    {
        return [];
    }

    public function roles(): HasMany
    {
        return $this->hasMany(RolePermission::class, 'permission_id', 'id');
    }
}
