<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class PickList extends BaseModel
{
    use HasUlids;

    protected $table = 'pick_lists';

    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'completed_at' => 'datetime',
        ];
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(Warehouse::class, 'warehouse_id', 'id');
    }

    public function fo(): BelongsTo
    {
        return $this->belongsTo(FulfillmentOrder::class, 'fo_id', 'id');
    }

    public function tasks(): HasMany
    {
        return $this->hasMany(PickTask::class, 'pick_list_id', 'id');
    }
}
