<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class PickTask extends BaseModel
{
    use HasUlids;

    protected $table = 'pick_tasks';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'seq' => 'integer',
            'qty' => 'integer',
            'picked_qty' => 'integer',
            'picked_at' => 'datetime',
        ];
    }

    public function pickList(): BelongsTo
    {
        return $this->belongsTo(\App\Models\PickList::class, 'pick_list_id', 'id');
    }

    public function foLine(): BelongsTo
    {
        return $this->belongsTo(\App\Models\FoLine::class, 'fo_line_id', 'id');
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Product::class, 'product_id', 'id');
    }

    public function bin(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Bin::class, 'bin_id', 'id');
    }

    public function batch(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Batch::class, 'batch_id', 'id');
    }
}
