<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class PoApproval extends BaseModel
{
    use HasUlids;

    protected $table = 'po_approvals';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'step' => 'integer',
            'decided_at' => 'datetime',
        ];
    }

    public function po(): BelongsTo
    {
        return $this->belongsTo(\App\Models\PurchaseOrder::class, 'po_id', 'id');
    }
}
