<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class PodAttachment extends BaseModel
{
    use HasUlids;

    protected $table = 'pod_attachments';

    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'size' => 'integer',
        ];
    }

    public function pod(): BelongsTo
    {
        return $this->belongsTo(ProofOfDelivery::class, 'pod_id', 'id');
    }
}
