<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class PoLine extends BaseModel
{
    use HasUlids;

    protected $table = 'po_lines';

    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'line_no' => 'integer',
            'qty' => 'integer',
            'price' => 'decimal:2',
            'received_qty' => 'integer',
            'damaged_qty' => 'integer',
            'rejected_qty' => 'integer',
        ];
    }

    public function po(): BelongsTo
    {
        return $this->belongsTo(PurchaseOrder::class, 'po_id', 'id');
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class, 'product_id', 'id');
    }

    public function shipmentLines(): HasMany
    {
        return $this->hasMany(ShipmentLine::class, 'po_line_id', 'id');
    }

    public function grnLines(): HasMany
    {
        return $this->hasMany(GrnLine::class, 'po_line_id', 'id');
    }
}
