<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class PrLine extends BaseModel
{
    use HasUlids;

    protected $table = 'pr_lines';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'line_no' => 'integer',
            'qty' => 'integer',
            'est_price' => 'decimal:2',
        ];
    }

    public function pr(): BelongsTo
    {
        return $this->belongsTo(\App\Models\PurchaseRequisition::class, 'pr_id', 'id');
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Product::class, 'product_id', 'id');
    }
}
