<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ProductStorageRequirement extends BaseModel
{
    protected $table = 'product_storage_requirements';

    protected $primaryKey = 'product_id';

    public $incrementing = false;

    protected $keyType = 'string';

    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'min_temp_c' => 'float',
            'max_temp_c' => 'float',
            'hazmat' => 'boolean',
        ];
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class, 'product_id', 'id');
    }
}
