<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Product extends BaseModel
{
    use HasUlids;

    protected $table = 'products';

    protected function casts(): array
    {
        return [
            'weight_kg' => 'float',
            'units_per_pallet' => 'integer',
            'purchase_price' => 'decimal:2',
            'tracks_expiry' => 'boolean',
            'reorder_min' => 'integer',
            'reorder_max' => 'integer',
            'length_cm' => 'float',
            'width_cm' => 'float',
            'height_cm' => 'float',
            'volume_m3' => 'float',
            'shelf_life_days' => 'integer',
            'active' => 'boolean',
        ];
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(\App\Models\ProductCategory::class, 'category_id', 'id');
    }

    public function baseUom(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Uom::class, 'base_uom_id', 'id');
    }

    public function homeWarehouse(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Warehouse::class, 'home_warehouse_id', 'id');
    }

    public function barcodes(): HasMany
    {
        return $this->hasMany(\App\Models\ProductBarcode::class, 'product_id', 'id');
    }

    public function suppliers(): HasMany
    {
        return $this->hasMany(\App\Models\ProductSupplier::class, 'product_id', 'id');
    }

    public function storageReq(): HasOne
    {
        return $this->hasOne(\App\Models\ProductStorageRequirement::class, 'product_id', 'id');
    }

    public function batches(): HasMany
    {
        return $this->hasMany(\App\Models\Batch::class, 'product_id', 'id');
    }

    public function balances(): HasMany
    {
        return $this->hasMany(\App\Models\InventoryBalance::class, 'product_id', 'id');
    }

    public function movements(): HasMany
    {
        return $this->hasMany(\App\Models\InventoryMovement::class, 'product_id', 'id');
    }

    public function prLines(): HasMany
    {
        return $this->hasMany(\App\Models\PrLine::class, 'product_id', 'id');
    }

    public function rfqLines(): HasMany
    {
        return $this->hasMany(\App\Models\RfqLine::class, 'product_id', 'id');
    }

    public function sqLines(): HasMany
    {
        return $this->hasMany(\App\Models\SupplierQuotationLine::class, 'product_id', 'id');
    }

    public function poLines(): HasMany
    {
        return $this->hasMany(\App\Models\PoLine::class, 'product_id', 'id');
    }

    public function shipmentLines(): HasMany
    {
        return $this->hasMany(\App\Models\ShipmentLine::class, 'product_id', 'id');
    }

    public function grnLines(): HasMany
    {
        return $this->hasMany(\App\Models\GrnLine::class, 'product_id', 'id');
    }

    public function putawayTasks(): HasMany
    {
        return $this->hasMany(\App\Models\PutawayTask::class, 'product_id', 'id');
    }

    public function quotationLines(): HasMany
    {
        return $this->hasMany(\App\Models\QuotationLine::class, 'product_id', 'id');
    }

    public function soLines(): HasMany
    {
        return $this->hasMany(\App\Models\SalesOrderLine::class, 'product_id', 'id');
    }

    public function foLines(): HasMany
    {
        return $this->hasMany(\App\Models\FoLine::class, 'product_id', 'id');
    }

    public function pickTasks(): HasMany
    {
        return $this->hasMany(\App\Models\PickTask::class, 'product_id', 'id');
    }

    public function reservations(): HasMany
    {
        return $this->hasMany(\App\Models\InventoryReservation::class, 'product_id', 'id');
    }

    public function allocations(): HasMany
    {
        return $this->hasMany(\App\Models\InventoryAllocation::class, 'product_id', 'id');
    }

    public function transferLines(): HasMany
    {
        return $this->hasMany(\App\Models\TransferLine::class, 'product_id', 'id');
    }

    public function countLines(): HasMany
    {
        return $this->hasMany(\App\Models\CountLine::class, 'product_id', 'id');
    }

    public function returnLines(): HasMany
    {
        return $this->hasMany(\App\Models\ReturnLine::class, 'product_id', 'id');
    }

    public function fixedBins(): HasMany
    {
        return $this->hasMany(\App\Models\Bin::class, 'fixed_product_id', 'id');
    }
}
