<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class ProofOfDelivery extends BaseModel
{
    use HasUlids;

    protected $table = 'proof_of_delivery';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'delivered_qty' => 'integer',
            'returned_qty' => 'integer',
            'gps_lat' => 'float',
            'gps_lng' => 'float',
            'gps_accuracy' => 'float',
            'at' => 'datetime',
        ];
    }

    public function delivery(): BelongsTo
    {
        return $this->belongsTo(\App\Models\DeliveryRecord::class, 'delivery_id', 'id');
    }

    public function trip(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Trip::class, 'trip_id', 'id');
    }

    public function stop(): BelongsTo
    {
        return $this->belongsTo(\App\Models\TripStop::class, 'stop_id', 'id');
    }

    public function fo(): BelongsTo
    {
        return $this->belongsTo(\App\Models\FulfillmentOrder::class, 'fo_id', 'id');
    }

    public function driver(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Driver::class, 'driver_id', 'id');
    }

    public function vehicle(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Vehicle::class, 'vehicle_id', 'id');
    }

    public function customer(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Customer::class, 'customer_id', 'id');
    }

    public function attachments(): HasMany
    {
        return $this->hasMany(\App\Models\PodAttachment::class, 'pod_id', 'id');
    }
}
