<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class PurchaseOrder extends BaseModel
{
    use HasUlids;

    protected $table = 'purchase_orders';

    protected function casts(): array
    {
        return [
            'total' => 'decimal:2',
            'due_date' => 'datetime',
            'approval_step' => 'integer',
            'open_qty' => 'integer',
            'approved_at' => 'datetime',
            'sent_at' => 'datetime',
            'confirmed_at' => 'datetime',
            'closed_at' => 'datetime',
        ];
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Supplier::class, 'supplier_id', 'id');
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Warehouse::class, 'warehouse_id', 'id');
    }

    public function rfq(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Rfq::class, 'rfq_id', 'id');
    }

    public function lines(): HasMany
    {
        return $this->hasMany(\App\Models\PoLine::class, 'po_id', 'id');
    }

    public function approvals(): HasMany
    {
        return $this->hasMany(\App\Models\PoApproval::class, 'po_id', 'id');
    }

    public function shipments(): HasMany
    {
        return $this->hasMany(\App\Models\InboundShipment::class, 'po_id', 'id');
    }

    public function grns(): HasMany
    {
        return $this->hasMany(\App\Models\GoodsReceipt::class, 'po_id', 'id');
    }
}
