<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class PurchaseRequisition extends BaseModel
{
    use HasUlids;

    protected $table = 'purchase_requisitions';

    protected function casts(): array
    {
        return [
            'need_date' => 'datetime',
            'submitted_at' => 'datetime',
            'approved_at' => 'datetime',
        ];
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Warehouse::class, 'warehouse_id', 'id');
    }

    public function lines(): HasMany
    {
        return $this->hasMany(\App\Models\PrLine::class, 'pr_id', 'id');
    }

    public function approvals(): HasMany
    {
        return $this->hasMany(\App\Models\PrApproval::class, 'pr_id', 'id');
    }

    public function rfqs(): HasMany
    {
        return $this->hasMany(\App\Models\Rfq::class, 'pr_id', 'id');
    }
}
