<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class PutawayTask extends BaseModel
{
    use HasUlids;

    protected $table = 'putaway_tasks';

    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'expiry_date' => 'datetime',
            'qty' => 'integer',
            'confirmed_at' => 'datetime',
        ];
    }

    public function grn(): BelongsTo
    {
        return $this->belongsTo(GoodsReceipt::class, 'grn_id', 'id');
    }

    public function grnLine(): BelongsTo
    {
        return $this->belongsTo(GrnLine::class, 'grn_line_id', 'id');
    }

    public function shipment(): BelongsTo
    {
        return $this->belongsTo(InboundShipment::class, 'shipment_id', 'id');
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class, 'product_id', 'id');
    }

    public function batch(): BelongsTo
    {
        return $this->belongsTo(Batch::class, 'batch_id', 'id');
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(Warehouse::class, 'warehouse_id', 'id');
    }

    public function suggestedBin(): BelongsTo
    {
        return $this->belongsTo(Bin::class, 'suggested_bin_id', 'id');
    }

    public function actualBin(): BelongsTo
    {
        return $this->belongsTo(Bin::class, 'actual_bin_id', 'id');
    }
}
