<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class QcResult extends BaseModel
{
    use HasUlids;

    protected $table = 'qc_results';

    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'qty' => 'integer',
            'at' => 'datetime',
        ];
    }

    public function grnLine(): BelongsTo
    {
        return $this->belongsTo(GrnLine::class, 'grn_line_id', 'id');
    }
}
