<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Quotation extends BaseModel
{
    use HasUlids;

    protected $table = 'quotations';
    protected $attributes = ['attachments' => '[]'];

    protected function casts(): array
    {
        return [
            'date' => 'datetime',
            'valid_until' => 'datetime',
            'attachments' => 'array',
        ];
    }

    public function customer(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Customer::class, 'customer_id', 'id');
    }

    public function lines(): HasMany
    {
        return $this->hasMany(\App\Models\QuotationLine::class, 'quotation_id', 'id');
    }

    public function so(): BelongsTo
    {
        return $this->belongsTo(\App\Models\SalesOrder::class, 'so_id', 'id');
    }
}
