<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class QuotationLine extends BaseModel
{
    use HasUlids;

    protected $table = 'quotation_lines';

    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'line_no' => 'integer',
            'qty' => 'integer',
            'price' => 'decimal:2',
            'disc_pct' => 'float',
        ];
    }

    public function quotation(): BelongsTo
    {
        return $this->belongsTo(Quotation::class, 'quotation_id', 'id');
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class, 'product_id', 'id');
    }
}
