<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Rack extends BaseModel
{
    use HasUlids;

    protected $table = 'racks';

    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'aisle' => 'integer',
            'rack_no' => 'integer',
            'levels' => 'integer',
            'active' => 'boolean',
        ];
    }

    public function zone(): BelongsTo
    {
        return $this->belongsTo(Zone::class, 'zone_id', 'id');
    }

    public function bins(): HasMany
    {
        return $this->hasMany(Bin::class, 'rack_id', 'id');
    }
}
