<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ReturnLine extends BaseModel
{
    use HasUlids;

    protected $table = 'return_lines';

    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'line_no' => 'integer',
            'qty' => 'integer',
            'expiry_date' => 'datetime',
            'inspected_qty' => 'integer',
        ];
    }

    public function ret(): BelongsTo
    {
        return $this->belongsTo(ReturnOrder::class, 'return_id', 'id');
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class, 'product_id', 'id');
    }

    public function batch(): BelongsTo
    {
        return $this->belongsTo(Batch::class, 'batch_id', 'id');
    }

    public function bin(): BelongsTo
    {
        return $this->belongsTo(Bin::class, 'bin_id', 'id');
    }
}
