<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ReturnReceiving extends BaseModel
{
    protected $table = 'return_receiving';
    protected $primaryKey = 'return_id';
    public $incrementing = false;
    protected $keyType = 'string';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'received_at' => 'datetime',
        ];
    }

    public function ret(): BelongsTo
    {
        return $this->belongsTo(\App\Models\ReturnOrder::class, 'return_id', 'id');
    }
}
