<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ReturnDecision extends BaseModel
{
    use HasUlids;

    protected $table = 'return_decisions';

    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'qty' => 'integer',
            'at' => 'datetime',
        ];
    }

    public function ret(): BelongsTo
    {
        return $this->belongsTo(ReturnOrder::class, 'return_id', 'id');
    }
}
