<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class ReturnOrder extends BaseModel
{
    use HasUlids;

    protected $table = 'returns';
    protected $attributes = ['attachments' => '[]'];

    protected function casts(): array
    {
        return [
            'attachments' => 'array',
            'decided_at' => 'datetime',
            'approved_at' => 'datetime',
            'received_at' => 'datetime',
            'inspected_at' => 'datetime',
            'closed_at' => 'datetime',
        ];
    }

    public function customer(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Customer::class, 'customer_id', 'id');
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Supplier::class, 'supplier_id', 'id');
    }

    public function fo(): BelongsTo
    {
        return $this->belongsTo(\App\Models\FulfillmentOrder::class, 'fo_id', 'id');
    }

    public function trip(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Trip::class, 'trip_id', 'id');
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Warehouse::class, 'warehouse_id', 'id');
    }

    public function lines(): HasMany
    {
        return $this->hasMany(\App\Models\ReturnLine::class, 'return_id', 'id');
    }

    public function receiving(): HasOne
    {
        return $this->hasOne(\App\Models\ReturnReceiving::class, 'return_id', 'id');
    }

    public function inspection(): HasOne
    {
        return $this->hasOne(\App\Models\ReturnInspection::class, 'return_id', 'id');
    }

    public function decisions(): HasMany
    {
        return $this->hasMany(\App\Models\ReturnDecision::class, 'return_id', 'id');
    }
}
