<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Rfq extends BaseModel
{
    use HasUlids;

    protected $table = 'rfqs';
    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'close_date' => 'datetime',
            'awarded_at' => 'datetime',
        ];
    }

    public function pr(): BelongsTo
    {
        return $this->belongsTo(\App\Models\PurchaseRequisition::class, 'pr_id', 'id');
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Warehouse::class, 'delivery_warehouse_id', 'id');
    }

    public function lines(): HasMany
    {
        return $this->hasMany(\App\Models\RfqLine::class, 'rfq_id', 'id');
    }

    public function suppliers(): HasMany
    {
        return $this->hasMany(\App\Models\RfqSupplier::class, 'rfq_id', 'id');
    }

    public function quotations(): HasMany
    {
        return $this->hasMany(\App\Models\SupplierQuotation::class, 'rfq_id', 'id');
    }

    public function awarded(): BelongsTo
    {
        return $this->belongsTo(\App\Models\SupplierQuotation::class, 'awarded_quotation_id', 'id');
    }

    public function pos(): HasMany
    {
        return $this->hasMany(\App\Models\PurchaseOrder::class, 'rfq_id', 'id');
    }
}
