<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;

class Route extends BaseModel
{
    use HasUlids;

    protected $table = 'routes';
    public $timestamps = false;

    protected function casts(): array
    {
        return [];
    }
}
