<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class SalesOrderLine extends BaseModel
{
    use HasUlids;

    protected $table = 'sales_order_lines';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'line_no' => 'integer',
            'qty' => 'integer',
            'price' => 'decimal:2',
            'disc_pct' => 'float',
            'reserved_qty' => 'integer',
            'allocated_qty' => 'integer',
            'picked_qty' => 'integer',
            'delivered_qty' => 'integer',
            'returned_qty' => 'integer',
        ];
    }

    public function so(): BelongsTo
    {
        return $this->belongsTo(\App\Models\SalesOrder::class, 'so_id', 'id');
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Product::class, 'product_id', 'id');
    }

    public function reservations(): HasMany
    {
        return $this->hasMany(\App\Models\InventoryReservation::class, 'so_line_id', 'id');
    }

    public function allocations(): HasMany
    {
        return $this->hasMany(\App\Models\InventoryAllocation::class, 'so_line_id', 'id');
    }

    public function foLines(): HasMany
    {
        return $this->hasMany(\App\Models\FoLine::class, 'so_line_id', 'id');
    }
}
