<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class SalesOrder extends BaseModel
{
    use HasUlids;

    protected $table = 'sales_orders';

    protected function casts(): array
    {
        return [
            'date' => 'datetime',
            'due_date' => 'datetime',
            'kg' => 'float',
            'cbm' => 'float',
        ];
    }

    public function customer(): BelongsTo
    {
        return $this->belongsTo(Customer::class, 'customer_id', 'id');
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(Warehouse::class, 'warehouse_id', 'id');
    }

    public function consolidation(): BelongsTo
    {
        return $this->belongsTo(OrderConsolidation::class, 'consolidation_id', 'id');
    }

    public function quotation(): HasOne
    {
        return $this->hasOne(Quotation::class, 'so_id', 'id');
    }

    public function lines(): HasMany
    {
        return $this->hasMany(SalesOrderLine::class, 'so_id', 'id');
    }

    public function reservations(): HasMany
    {
        return $this->hasMany(InventoryReservation::class, 'so_id', 'id');
    }

    public function fos(): HasMany
    {
        return $this->hasMany(FulfillmentOrder::class, 'so_id', 'id');
    }

    public function stops(): HasMany
    {
        return $this->hasMany(TripStop::class, 'so_id', 'id');
    }
}
