<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class ShipmentLine extends BaseModel
{
    use HasUlids;

    protected $table = 'shipment_lines';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'line_no' => 'integer',
            'ordered_qty' => 'integer',
            'accepted_qty' => 'integer',
            'damaged_qty' => 'integer',
            'rejected_qty' => 'integer',
            'mfg_date' => 'datetime',
            'expiry_date' => 'datetime',
        ];
    }

    public function shipment(): BelongsTo
    {
        return $this->belongsTo(\App\Models\InboundShipment::class, 'shipment_id', 'id');
    }

    public function poLine(): BelongsTo
    {
        return $this->belongsTo(\App\Models\PoLine::class, 'po_line_id', 'id');
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Product::class, 'product_id', 'id');
    }

    public function suggestedBin(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Bin::class, 'suggested_bin_id', 'id');
    }

    public function grnLines(): HasMany
    {
        return $this->hasMany(\App\Models\GrnLine::class, 'shipment_line_id', 'id');
    }
}
