<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class StagingEntry extends BaseModel
{
    use HasUlids;

    protected $table = 'staging_entries';

    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'qty' => 'integer',
            'cleared_at' => 'datetime',
        ];
    }

    public function bin(): BelongsTo
    {
        return $this->belongsTo(Bin::class, 'bin_id', 'id');
    }
}
