<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class SupplierQuotation extends BaseModel
{
    use HasUlids;

    protected $table = 'supplier_quotations';
    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'date' => 'datetime',
            'valid_until' => 'datetime',
            'min_order' => 'integer',
            'lead_days' => 'integer',
            'recommended' => 'boolean',
            'score' => 'float',
        ];
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Supplier::class, 'supplier_id', 'id');
    }

    public function rfq(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Rfq::class, 'rfq_id', 'id');
    }

    public function awardedFor(): HasOne
    {
        return $this->hasOne(\App\Models\Rfq::class, 'awarded_quotation_id', 'id');
    }

    public function lines(): HasMany
    {
        return $this->hasMany(\App\Models\SupplierQuotationLine::class, 'quotation_id', 'id');
    }
}
