<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Supplier extends BaseModel
{
    use HasUlids;

    protected $table = 'suppliers';

    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'lead_days' => 'integer',
            'otif' => 'float',
            'fill_rate' => 'float',
            'score' => 'float',
            'orders_count' => 'integer',
            'total_value' => 'decimal:2',
            'min_order' => 'decimal:2',
            'is_new' => 'boolean',
            'active' => 'boolean',
        ];
    }

    public function products(): HasMany
    {
        return $this->hasMany(ProductSupplier::class, 'supplier_id', 'id');
    }

    public function quotations(): HasMany
    {
        return $this->hasMany(SupplierQuotation::class, 'supplier_id', 'id');
    }

    public function rfqs(): HasMany
    {
        return $this->hasMany(RfqSupplier::class, 'supplier_id', 'id');
    }

    public function pos(): HasMany
    {
        return $this->hasMany(PurchaseOrder::class, 'supplier_id', 'id');
    }

    public function shipments(): HasMany
    {
        return $this->hasMany(InboundShipment::class, 'supplier_id', 'id');
    }

    public function grns(): HasMany
    {
        return $this->hasMany(GoodsReceipt::class, 'supplier_id', 'id');
    }

    public function batches(): HasMany
    {
        return $this->hasMany(Batch::class, 'supplier_id', 'id');
    }

    public function returns(): HasMany
    {
        return $this->hasMany(ReturnOrder::class, 'supplier_id', 'id');
    }
}
