<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class SupplierQuotationLine extends BaseModel
{
    use HasUlids;

    protected $table = 'supplier_quotation_lines';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'qty' => 'integer',
            'price' => 'decimal:2',
            'vat_pct' => 'float',
            'lead_days' => 'integer',
        ];
    }

    public function quotation(): BelongsTo
    {
        return $this->belongsTo(\App\Models\SupplierQuotation::class, 'quotation_id', 'id');
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Product::class, 'product_id', 'id');
    }
}
