<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class TripStop extends BaseModel
{
    use HasUlids;

    protected $table = 'trip_stops';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'seq' => 'integer',
            'items' => 'integer',
            'kg' => 'float',
            'map_x' => 'float',
            'map_y' => 'float',
            'arrived_at' => 'datetime',
            'completed_at' => 'datetime',
        ];
    }

    public function trip(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Trip::class, 'trip_id', 'id');
    }

    public function customer(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Customer::class, 'customer_id', 'id');
    }

    public function so(): BelongsTo
    {
        return $this->belongsTo(\App\Models\SalesOrder::class, 'so_id', 'id');
    }

    public function fo(): BelongsTo
    {
        return $this->belongsTo(\App\Models\FulfillmentOrder::class, 'fo_id', 'id');
    }

    public function tripOrders(): HasMany
    {
        return $this->hasMany(\App\Models\TripOrder::class, 'stop_id', 'id');
    }

    public function delivery(): HasOne
    {
        return $this->hasOne(\App\Models\DeliveryRecord::class, 'stop_id', 'id');
    }

    public function pod(): HasOne
    {
        return $this->hasOne(\App\Models\ProofOfDelivery::class, 'stop_id', 'id');
    }
}
