<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\BelongsTo;

class TripCost extends BaseModel
{
    protected $table = 'trip_costs';

    protected $primaryKey = 'trip_id';

    public $incrementing = false;

    protected $keyType = 'string';

    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'fuel' => 'float',
            'driver' => 'float',
            'ot' => 'float',
            'maint' => 'float',
            'dep' => 'float',
            'tolls' => 'float',
            'parking' => 'float',
            'third' => 'float',
            'other' => 'float',
        ];
    }

    public function trip(): BelongsTo
    {
        return $this->belongsTo(Trip::class, 'trip_id', 'id');
    }
}
