<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class TripOrder extends BaseModel
{
    use HasUlids;

    protected $table = 'trip_orders';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'loaded' => 'boolean',
            'loaded_at' => 'datetime',
            'load_seq' => 'integer',
        ];
    }

    public function trip(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Trip::class, 'trip_id', 'id');
    }

    public function fo(): BelongsTo
    {
        return $this->belongsTo(\App\Models\FulfillmentOrder::class, 'fo_id', 'id');
    }

    public function stop(): BelongsTo
    {
        return $this->belongsTo(\App\Models\TripStop::class, 'stop_id', 'id');
    }
}
