<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Trip extends BaseModel
{
    use HasUlids;

    protected $table = 'trips';

    protected function casts(): array
    {
        return [
            'date' => 'datetime',
            'km' => 'float',
            'actual_start' => 'datetime',
            'actual_end' => 'datetime',
            'delay_min' => 'integer',
            'kg' => 'float',
            'cbm' => 'float',
            'pallets' => 'integer',
            'dispatched_at' => 'datetime',
            'closed_at' => 'datetime',
        ];
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(Warehouse::class, 'warehouse_id', 'id');
    }

    public function vehicle(): BelongsTo
    {
        return $this->belongsTo(Vehicle::class, 'vehicle_id', 'id');
    }

    public function driver(): BelongsTo
    {
        return $this->belongsTo(Driver::class, 'driver_id', 'id');
    }

    public function consolidation(): BelongsTo
    {
        return $this->belongsTo(OrderConsolidation::class, 'consolidation_id', 'id');
    }

    public function stops(): HasMany
    {
        return $this->hasMany(TripStop::class, 'trip_id', 'id');
    }

    public function orders(): HasMany
    {
        return $this->hasMany(TripOrder::class, 'trip_id', 'id');
    }

    public function fos(): HasMany
    {
        return $this->hasMany(FulfillmentOrder::class, 'trip_id', 'id');
    }

    public function events(): HasMany
    {
        return $this->hasMany(TripEvent::class, 'trip_id', 'id');
    }

    public function cost(): HasOne
    {
        return $this->hasOne(TripCost::class, 'trip_id', 'id');
    }

    public function loadingPlans(): HasMany
    {
        return $this->hasMany(LoadingPlan::class, 'trip_id', 'id');
    }

    public function dispatch(): HasOne
    {
        return $this->hasOne(DispatchRecord::class, 'trip_id', 'id');
    }

    public function deliveries(): HasMany
    {
        return $this->hasMany(DeliveryRecord::class, 'trip_id', 'id');
    }

    public function pods(): HasMany
    {
        return $this->hasMany(ProofOfDelivery::class, 'trip_id', 'id');
    }

    public function returns(): HasMany
    {
        return $this->hasMany(ReturnOrder::class, 'trip_id', 'id');
    }
}
