<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Uom extends BaseModel
{
    use HasUlids;

    protected $table = 'uoms';
    public $timestamps = false;

    protected function casts(): array
    {
        return [];
    }

    public function products(): HasMany
    {
        return $this->hasMany(\App\Models\Product::class, 'base_uom_id', 'id');
    }

    public function barcodes(): HasMany
    {
        return $this->hasMany(\App\Models\ProductBarcode::class, 'uom_id', 'id');
    }
}
