<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\BelongsTo;

class UserRole extends BaseModel
{
    protected $table = 'user_roles';
    /** Composite key (user_id, role_id): write through the query builder or relations, not save(). */
    protected $primaryKey = null;
    public $incrementing = false;
    public $timestamps = false;

    protected function casts(): array
    {
        return [];
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(\App\Models\User::class, 'user_id', 'id');
    }

    public function role(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Role::class, 'role_id', 'id');
    }
}
