<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Vehicle extends BaseModel
{
    use HasUlids;

    protected $table = 'vehicles';

    protected function casts(): array
    {
        return [
            'year' => 'integer',
            'max_kg' => 'float',
            'max_cbm' => 'float',
            'pallets' => 'integer',
            'compartments' => 'integer',
            'odometer' => 'integer',
            'engine_hours' => 'integer',
            'tank_l' => 'integer',
            'avg_km_l' => 'float',
            'reg_expiry' => 'datetime',
            'insurance_expiry' => 'datetime',
            'inspection_expiry' => 'datetime',
            'op_card_expiry' => 'datetime',
            'last_maint_date' => 'datetime',
            'next_maint_date' => 'datetime',
            'next_maint_km' => 'integer',
            'gps_online' => 'boolean',
            'last_sync_at' => 'datetime',
            'fuel_pct' => 'integer',
            'map_x' => 'float',
            'map_y' => 'float',
            'lat' => 'float',
            'lng' => 'float',
            'active' => 'boolean',
        ];
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(Warehouse::class, 'warehouse_id', 'id');
    }

    public function trips(): HasMany
    {
        return $this->hasMany(Trip::class, 'vehicle_id', 'id');
    }

    public function drivers(): HasMany
    {
        return $this->hasMany(Driver::class, 'default_vehicle_id', 'id');
    }

    public function maintenance(): HasMany
    {
        return $this->hasMany(MaintenanceOrder::class, 'vehicle_id', 'id');
    }

    public function fuel(): HasMany
    {
        return $this->hasMany(FuelRecord::class, 'vehicle_id', 'id');
    }

    public function loadingPlans(): HasMany
    {
        return $this->hasMany(LoadingPlan::class, 'vehicle_id', 'id');
    }

    public function dispatches(): HasMany
    {
        return $this->hasMany(DispatchRecord::class, 'vehicle_id', 'id');
    }

    public function pods(): HasMany
    {
        return $this->hasMany(ProofOfDelivery::class, 'vehicle_id', 'id');
    }

    public function deliveries(): HasMany
    {
        return $this->hasMany(DeliveryRecord::class, 'vehicle_id', 'id');
    }
}
