<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class WarehouseTransfer extends BaseModel
{
    use HasUlids;

    protected $table = 'warehouse_transfers';

    protected function casts(): array
    {
        return [
            'date' => 'datetime',
            'eta' => 'datetime',
            'approved_at' => 'datetime',
            'shipped_at' => 'datetime',
            'received_at' => 'datetime',
            'closed_at' => 'datetime',
        ];
    }

    public function fromWarehouse(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Warehouse::class, 'from_warehouse_id', 'id');
    }

    public function toWarehouse(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Warehouse::class, 'to_warehouse_id', 'id');
    }

    public function lines(): HasMany
    {
        return $this->hasMany(\App\Models\TransferLine::class, 'transfer_id', 'id');
    }
}
