<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Warehouse extends BaseModel
{
    use HasUlids;

    protected $table = 'warehouses';

    const UPDATED_AT = null;

    protected function casts(): array
    {
        return [
            'area_m2' => 'float',
            'docks' => 'integer',
            'open_date' => 'datetime',
            'active' => 'boolean',
        ];
    }

    public function zones(): HasMany
    {
        return $this->hasMany(Zone::class, 'warehouse_id', 'id');
    }

    public function bins(): HasMany
    {
        return $this->hasMany(Bin::class, 'warehouse_id', 'id');
    }

    public function users(): HasMany
    {
        return $this->hasMany(UserWarehouse::class, 'warehouse_id', 'id');
    }

    public function products(): HasMany
    {
        return $this->hasMany(Product::class, 'home_warehouse_id', 'id');
    }

    public function balances(): HasMany
    {
        return $this->hasMany(InventoryBalance::class, 'warehouse_id', 'id');
    }

    public function vehicles(): HasMany
    {
        return $this->hasMany(Vehicle::class, 'warehouse_id', 'id');
    }

    public function prs(): HasMany
    {
        return $this->hasMany(PurchaseRequisition::class, 'warehouse_id', 'id');
    }

    public function pos(): HasMany
    {
        return $this->hasMany(PurchaseOrder::class, 'warehouse_id', 'id');
    }

    public function rfqs(): HasMany
    {
        return $this->hasMany(Rfq::class, 'delivery_warehouse_id', 'id');
    }

    public function shipments(): HasMany
    {
        return $this->hasMany(InboundShipment::class, 'warehouse_id', 'id');
    }

    public function grns(): HasMany
    {
        return $this->hasMany(GoodsReceipt::class, 'warehouse_id', 'id');
    }

    public function putaways(): HasMany
    {
        return $this->hasMany(PutawayTask::class, 'warehouse_id', 'id');
    }

    public function salesOrders(): HasMany
    {
        return $this->hasMany(SalesOrder::class, 'warehouse_id', 'id');
    }

    public function fos(): HasMany
    {
        return $this->hasMany(FulfillmentOrder::class, 'warehouse_id', 'id');
    }

    public function pickLists(): HasMany
    {
        return $this->hasMany(PickList::class, 'warehouse_id', 'id');
    }

    public function transfersOut(): HasMany
    {
        return $this->hasMany(WarehouseTransfer::class, 'from_warehouse_id', 'id');
    }

    public function transfersIn(): HasMany
    {
        return $this->hasMany(WarehouseTransfer::class, 'to_warehouse_id', 'id');
    }

    public function counts(): HasMany
    {
        return $this->hasMany(InventoryCount::class, 'warehouse_id', 'id');
    }

    public function trips(): HasMany
    {
        return $this->hasMany(Trip::class, 'warehouse_id', 'id');
    }

    public function returns(): HasMany
    {
        return $this->hasMany(ReturnOrder::class, 'warehouse_id', 'id');
    }

    public function consolidations(): HasMany
    {
        return $this->hasMany(OrderConsolidation::class, 'warehouse_id', 'id');
    }

    public function reservations(): HasMany
    {
        return $this->hasMany(InventoryReservation::class, 'warehouse_id', 'id');
    }

    public function allocations(): HasMany
    {
        return $this->hasMany(InventoryAllocation::class, 'warehouse_id', 'id');
    }

    public function docks_(): HasMany
    {
        return $this->hasMany(DockAppointment::class, 'warehouse_id', 'id');
    }

    public function staff(): HasMany
    {
        return $this->hasMany(StaffAssignment::class, 'warehouse_id', 'id');
    }
}
