<?php

// GENERATED by tools/prisma-to-laravel.mjs. Put hand-written behaviour in services or traits, or re-run the generator.

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Zone extends BaseModel
{
    use HasUlids;

    protected $table = 'zones';
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'min_temp_c' => 'float',
            'max_temp_c' => 'float',
            'capacity_units' => 'integer',
            'max_kg' => 'float',
            'active' => 'boolean',
        ];
    }

    public function warehouse(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Warehouse::class, 'warehouse_id', 'id');
    }

    public function racks(): HasMany
    {
        return $this->hasMany(\App\Models\Rack::class, 'zone_id', 'id');
    }

    public function bins(): HasMany
    {
        return $this->hasMany(\App\Models\Bin::class, 'zone_id', 'id');
    }

    public function counts(): HasMany
    {
        return $this->hasMany(\App\Models\InventoryCount::class, 'zone_id', 'id');
    }
}
