// One-off exporter: the reference system's shared package (enums, state machines, labels, permissions)
// -> config/scm.php (server) + resources/js/shared/constants.json (Vue client).
// Usage: node tools/export-shared.mjs "<path to reference>/packages/shared/dist/index.js"
// After the reference system is retired, edit config/scm.php and constants.json directly.
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const distPath = process.argv[2];
if (!distPath) { console.error('pass the path to packages/shared/dist/index.js'); process.exit(1); }
const shared = createRequire(import.meta.url)(path.resolve(distPath));

const isPlain = (v) => v !== null && typeof v === 'object' && !('_def' in v) && !('safeParse' in v);
const data = {};
for (const [k, v] of Object.entries(shared)) {
  if (typeof v === 'function') continue;
  if (Array.isArray(v) || isPlain(v)) {
    try { data[k] = JSON.parse(JSON.stringify(v)); } catch { /* skip non-serializable */ }
  }
}

const php = (v, ind = 1) => {
  const pad = '    '.repeat(ind);
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'string') return "'" + v.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (Array.isArray(v)) {
    if (v.every((x) => typeof x !== 'object' || x === null)) return '[' + v.map((x) => php(x, ind + 1)).join(', ') + ']';
    return '[\n' + v.map((x) => pad + '    ' + php(x, ind + 1) + ',').join('\n') + '\n' + pad + ']';
  }
  const entries = Object.entries(v);
  if (!entries.length) return '[]';
  return '[\n' + entries.map(([k, x]) => pad + '    ' + php(k) + ' => ' + php(x, ind + 1) + ',').join('\n') + '\n' + pad + ']';
};

const out = '<?php\n\n// GENERATED by tools/export-shared.mjs from the reference shared package.\n'
  + '// Status values, state machines, labels and the permission catalogue. Read with config(\'scm.KEY\').\n\n'
  + 'return ' + php(data, 0) + ';\n';
fs.writeFileSync(path.join(ROOT, 'config/scm.php'), out);
fs.mkdirSync(path.join(ROOT, 'resources/js/shared'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'resources/js/shared/constants.json'), JSON.stringify(data, null, 1));
console.log('exported ' + Object.keys(data).length + ' constants');
